# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-alegreya-sans-sc' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Alegreya Sans SC'
  homepage 'https://fonts.google.com/specimen/Alegreya+Sans+SC'

  font 'ofl/alegreyasanssc/AlegreyaSansSC-Black.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-BlackItalic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Bold.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-BoldItalic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-ExtraBold.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-ExtraBoldItalic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Italic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Light.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-LightItalic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Medium.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-MediumItalic.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Regular.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-Thin.ttf'
  font 'ofl/alegreyasanssc/AlegreyaSansSC-ThinItalic.ttf'
end
