cask "font-iosevka-nerd-font" do
  version "2.2.2"
  sha256 "c9c661d28756abad70bea9339dd3673548737214ebec8e8481c0966cedc56931"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Iosevka.zip"
  name "Iosevka Nerd Font (Iosevka)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  font "Iosevka Bold Nerd Font Complete.ttf"
  font "Iosevka Term Bold Nerd Font Complete.ttf"
  font "Iosevka Bold Nerd Font Complete Mono.ttf"
  font "Iosevka Term Bold Nerd Font Complete Mono.ttf"
  font "Iosevka Term Heavy Italic Nerd Font Complete.ttf"
  font "Iosevka Heavy Italic Nerd Font Complete.ttf"
  font "Iosevka Heavy Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Heavy Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Thin Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Thin Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Thin Oblique Nerd Font Complete.ttf"
  font "Iosevka Thin Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Bold Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Bold Italic Nerd Font Complete.ttf"
  font "Iosevka Term Bold Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Bold Italic Nerd Font Complete.ttf"
  font "Iosevka Light Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Light Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Light Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Light Oblique Nerd Font Complete.ttf"
  font "Iosevka Bold Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Bold Oblique Nerd Font Complete.ttf"
  font "Iosevka Bold Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Bold Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Medium Nerd Font Complete Mono.ttf"
  font "Iosevka Term Medium Nerd Font Complete.ttf"
  font "Iosevka Medium Nerd Font Complete Mono.ttf"
  font "Iosevka Medium Nerd Font Complete.ttf"
  font "Iosevka Term Extralight Nerd Font Complete Mono.ttf"
  font "Iosevka Term Extralight Nerd Font Complete.ttf"
  font "Iosevka Extralight Nerd Font Complete Mono.ttf"
  font "Iosevka Extralight Nerd Font Complete.ttf"
  font "Iosevka Medium Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Medium Oblique Nerd Font Complete.ttf"
  font "Iosevka Medium Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Medium Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Extralight Italic Nerd Font Complete.ttf"
  font "Iosevka Extralight Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Extralight Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Extralight Italic Nerd Font Complete.ttf"
  font "Iosevka Term Nerd Font Complete Mono.ttf"
  font "Iosevka Nerd Font Complete.ttf"
  font "Iosevka Term Nerd Font Complete.ttf"
  font "Iosevka Nerd Font Complete Mono.ttf"
  font "Iosevka Heavy Nerd Font Complete.ttf"
  font "Iosevka Term Heavy Nerd Font Complete Mono.ttf"
  font "Iosevka Heavy Nerd Font Complete Mono.ttf"
  font "Iosevka Term Heavy Nerd Font Complete.ttf"
  font "Iosevka Thin Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Thin Italic Nerd Font Complete.ttf"
  font "Iosevka Thin Italic Nerd Font Complete.ttf"
  font "Iosevka Term Thin Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Thin Nerd Font Complete.ttf"
  font "Iosevka Term Thin Nerd Font Complete.ttf"
  font "Iosevka Term Thin Nerd Font Complete Mono.ttf"
  font "Iosevka Thin Nerd Font Complete Mono.ttf"
  font "Iosevka Medium Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Medium Italic Nerd Font Complete.ttf"
  font "Iosevka Term Medium Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Medium Italic Nerd Font Complete.ttf"
  font "Iosevka Extralight Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Extralight Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Extralight Oblique Nerd Font Complete.ttf"
  font "Iosevka Extralight Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Oblique Nerd Font Complete.ttf"
  font "Iosevka Oblique Nerd Font Complete.ttf"
  font "Iosevka Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Term Italic Nerd Font Complete.ttf"
  font "Iosevka Italic Nerd Font Complete.ttf"
  font "Iosevka Heavy Oblique Nerd Font Complete.ttf"
  font "Iosevka Term Heavy Oblique Nerd Font Complete.ttf"
  font "Iosevka Heavy Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Term Heavy Oblique Nerd Font Complete Mono.ttf"
  font "Iosevka Light Nerd Font Complete.ttf"
  font "Iosevka Light Nerd Font Complete Mono.ttf"
  font "Iosevka Term Light Nerd Font Complete.ttf"
  font "Iosevka Term Light Nerd Font Complete Mono.ttf"
  font "Iosevka Light Italic Nerd Font Complete Mono.ttf"
  font "Iosevka Light Italic Nerd Font Complete.ttf"
  font "Iosevka Term Light Italic Nerd Font Complete.ttf"
  font "Iosevka Term Light Italic Nerd Font Complete Mono.ttf"
end
