cask 'font-grenze' do
  version '1.002'
  sha256 'ce89d7bf4368eed4656dce1299d914831119813b7e52723b9d18667299e069d0'

  url 'https://www.omnibus-type.com/wp-content/uploads/Grenze.zip'
  name 'Grenze'
  homepage 'https://www.omnibus-type.com/fonts/Grenze/'

  font 'Grenze/otf/Grenze-Black.otf'
  font 'Grenze/otf/Grenze-BlackItalic.otf'
  font 'Grenze/otf/Grenze-Bold.otf'
  font 'Grenze/otf/Grenze-BoldItalic.otf'
  font 'Grenze/otf/Grenze-ExtraBold.otf'
  font 'Grenze/otf/Grenze-ExtraBoldItalic.otf'
  font 'Grenze/otf/Grenze-ExtraLight.otf'
  font 'Grenze/otf/Grenze-ExtraLightItalic.otf'
  font 'Grenze/otf/Grenze-Italic.otf'
  font 'Grenze/otf/Grenze-Light.otf'
  font 'Grenze/otf/Grenze-LightItalic.otf'
  font 'Grenze/otf/Grenze-Medium.otf'
  font 'Grenze/otf/Grenze-MediumItalic.otf'
  font 'Grenze/otf/Grenze-Regular.otf'
  font 'Grenze/otf/Grenze-SemiBold.otf'
  font 'Grenze/otf/Grenze-SemiBoldItalic.otf'
  font 'Grenze/otf/Grenze-Thin.otf'
  font 'Grenze/otf/Grenze-ThinItalic.otf'
end
