# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-moul' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/moul/Moul.ttf'
  name 'Moul'
  homepage 'https://fonts.google.com/specimen/Moul'

  font 'Moul.ttf'
end
