# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-ibarra-real-nova' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Ibarra Real Nova'
  homepage 'https://fonts.google.com/specimen/Ibarra+Real+Nova'

  font 'ofl/ibarrarealnova/IbarraRealNova-Bold.ttf'
  font 'ofl/ibarrarealnova/IbarraRealNova-BoldItalic.ttf'
  font 'ofl/ibarrarealnova/IbarraRealNova-Italic.ttf'
  font 'ofl/ibarrarealnova/IbarraRealNova-Regular.ttf'
  font 'ofl/ibarrarealnova/IbarraRealNova-SemiBold.ttf'
  font 'ofl/ibarrarealnova/IbarraRealNova-SemiBoldItalic.ttf'
end
