# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-spirax' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/spirax/Spirax-Regular.ttf'
  name 'Spirax'
  homepage 'https://fonts.google.com/specimen/Spirax'

  font 'Spirax-Regular.ttf'
end
