# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-cormorant-sc' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Cormorant SC'
  homepage 'https://fonts.google.com/specimen/Cormorant+SC'

  font 'ofl/cormorantsc/CormorantSC-Bold.ttf'
  font 'ofl/cormorantsc/CormorantSC-Light.ttf'
  font 'ofl/cormorantsc/CormorantSC-Medium.ttf'
  font 'ofl/cormorantsc/CormorantSC-Regular.ttf'
  font 'ofl/cormorantsc/CormorantSC-SemiBold.ttf'
end
