# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-tenali-ramakrishna' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/tenaliramakrishna/TenaliRamakrishna-Regular.ttf'
  name 'Tenali Ramakrishna'
  homepage 'https://fonts.google.com/specimen/Tenali+Ramakrishna'

  font 'TenaliRamakrishna-Regular.ttf'
end
