# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-athiti' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Athiti'
  homepage 'https://fonts.google.com/specimen/Athiti'

  font 'ofl/athiti/Athiti-Bold.ttf'
  font 'ofl/athiti/Athiti-ExtraLight.ttf'
  font 'ofl/athiti/Athiti-Light.ttf'
  font 'ofl/athiti/Athiti-Medium.ttf'
  font 'ofl/athiti/Athiti-Regular.ttf'
  font 'ofl/athiti/Athiti-SemiBold.ttf'
end
