# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-chewy' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/apache/chewy/Chewy-Regular.ttf'
  name 'Chewy'
  homepage 'https://fonts.google.com/specimen/Chewy'

  font 'Chewy-Regular.ttf'
end
