cask "font-overpass" do
  version "3.0.4"
  sha256 "d0f510f01bd734eabc0967c4838f860bca8bd97369fda4607819cb15ec899853"

  url "https://github.com/RedHatOfficial/Overpass/archive/refs/tags/#{version}.zip",
      verified: "github.com/RedHatOfficial/Overpass/"
  name "Overpass"
  homepage "https://overpassfont.org/"

  font "desktop-fonts/overpass/overpass-bold-italic.otf"
  font "desktop-fonts/overpass/overpass-bold.otf"
  font "desktop-fonts/overpass/overpass-extrabold-italic.otf"
  font "desktop-fonts/overpass/overpass-extrabold.otf"
  font "desktop-fonts/overpass/overpass-extralight-italic.otf"
  font "desktop-fonts/overpass/overpass-extralight.otf"
  font "desktop-fonts/overpass/overpass-heavy-italic.otf"
  font "desktop-fonts/overpass/overpass-heavy.otf"
  font "desktop-fonts/overpass/overpass-italic.otf"
  font "desktop-fonts/overpass/overpass-light-italic.otf"
  font "desktop-fonts/overpass/overpass-light.otf"
  font "desktop-fonts/overpass/overpass-regular.otf"
  font "desktop-fonts/overpass/overpass-semibold-italic.otf"
  font "desktop-fonts/overpass/overpass-semibold.otf"
  font "desktop-fonts/overpass/overpass-thin-italic.otf"
  font "desktop-fonts/overpass/overpass-thin.otf"
  font "desktop-fonts/overpass-mono/overpass-mono-bold.otf"
  font "desktop-fonts/overpass-mono/overpass-mono-light.otf"
  font "desktop-fonts/overpass-mono/overpass-mono-regular.otf"
  font "desktop-fonts/overpass-mono/overpass-mono-semibold.otf"
end
