class FontMesloLg < Cask
  url 'https://github.com/andreberg/Meslo-Font/raw/master/dist/v1.2.1/Meslo%20LG%20v1.2.1.zip'
  homepage 'https://github.com/andreberg/Meslo-Font'
  version '1.21'
  sha1 '23cc2b1f4ed16f82054b127a8d3653516731f919'
  font 'Meslo LG v1.2.1/MesloLGL-Bold.ttf'
  font 'Meslo LG v1.2.1/MesloLGL-BoldItalic.ttf'
  font 'Meslo LG v1.2.1/MesloLGL-Italic.ttf'
  font 'Meslo LG v1.2.1/MesloLGL-Regular.ttf'
  font 'Meslo LG v1.2.1/MesloLGM-Bold.ttf'
  font 'Meslo LG v1.2.1/MesloLGM-BoldItalic.ttf'
  font 'Meslo LG v1.2.1/MesloLGM-Italic.ttf'
  font 'Meslo LG v1.2.1/MesloLGM-Regular.ttf'
  font 'Meslo LG v1.2.1/MesloLGS-Bold.ttf'
  font 'Meslo LG v1.2.1/MesloLGS-BoldItalic.ttf'
  font 'Meslo LG v1.2.1/MesloLGS-Italic.ttf'
  font 'Meslo LG v1.2.1/MesloLGS-Regular.ttf'
end
