cask "font-mona-sans" do
  version "1.0.1"
  sha256 "c5e44e736b72bbbd47ae7fecfde8f0c149ba2c0a436d27a2f1ec6392ba3ecd0b"

  url "https://github.com/github/mona-sans/releases/download/v#{version}/MonaSans.zip"
  name "Mona-Sans"
  desc "Mona Sans, a variable font from GitHub"
  homepage "https://github.com/github/mona-sans"

  font "Mona Sans/OTF/Mona-Sans-Black.otf"
  font "Mona Sans/OTF/Mona-Sans-BlackItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-BlackNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-BlackNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-BlackWide.otf"
  font "Mona Sans/OTF/Mona-Sans-BlackWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-Bold.otf"
  font "Mona Sans/OTF/Mona-Sans-BoldItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-BoldNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-BoldNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-BoldWide.otf"
  font "Mona Sans/OTF/Mona-Sans-BoldWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBold.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBoldItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBoldNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBoldNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBoldWide.otf"
  font "Mona Sans/OTF/Mona-Sans-ExtraBoldWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-Light.otf"
  font "Mona Sans/OTF/Mona-Sans-LightItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-LightNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-LightNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-LightWide.otf"
  font "Mona Sans/OTF/Mona-Sans-LightWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-Medium.otf"
  font "Mona Sans/OTF/Mona-Sans-MediumItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-MediumNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-MediumNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-MediumWide.otf"
  font "Mona Sans/OTF/Mona-Sans-MediumWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-Regular.otf"
  font "Mona Sans/OTF/Mona-Sans-RegularItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-RegularNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-RegularNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-RegularWide.otf"
  font "Mona Sans/OTF/Mona-Sans-RegularWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBold.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBoldItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBoldNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBoldNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBoldWide.otf"
  font "Mona Sans/OTF/Mona-Sans-SemiBoldWideItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLight.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLightItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLightNarrow.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLightNarrowItalic.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLightWide.otf"
  font "Mona Sans/OTF/Mona-Sans-UltraLightWideItalic.otf"

  # No zap stanza required
end
