class FontSourceSansPro < Cask
  url 'http://downloads.sourceforge.net/sourceforge/sourcesans.adobe/SourceSansPro_FontsOnly-1.050.zip'
  homepage 'http://store1.adobe.com/cfusion/store/html/index.cfm?store=OLS-US&event=displayFontPackage&code=1959'
  version '1.050'
  sha256 'c379f5ef53981757b9aa115cfd0775e9fa92175f5d611ab3bbe57689fa3c5f00'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-Black.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-BlackIt.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-Bold.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-BoldIt.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-ExtraLight.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-ExtraLightIt.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-It.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-Light.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-LightIt.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-Regular.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-Semibold.otf'
  font 'SourceSansPro_FontsOnly-1.050/OTF/SourceSansPro-SemiboldIt.otf'
end
