class FontDejavuSans < Cask
  url 'http://downloads.sourceforge.net/sourceforge/dejavu/dejavu-fonts-ttf-2.34.zip'
  homepage 'http://dejavu-fonts.org/wiki/Main_Page'
  version '2.34'
  sha256 'f6b806b4aa0ea36a8d0f2c46dcd5afa6743773930024e562980c4cd0f9230792'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-ExtraLight.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-BoldItalic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-Italic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-BoldItalic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-Italic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed.ttf'
end
