cask "font-coelacanth" do
  version "0.006"
  sha256 "6926eab323cc893b7f5c6115514421c7b8d96d23376c8181e8342219816f925c"

  url "https://github.com/Fuzzypeg/Coelacanth/releases/download/v#{version}/coelacanth_v#{version}.zip"
  appcast "https://github.com/Fuzzypeg/Coelacanth/releases.atom"
  name "Coelacanth"
  desc "Serif typeface inspired by Bruce Rogers' Centaur"
  homepage "https://github.com/Fuzzypeg/Coelacanth"

  font "Coelacanth.otf"
  font "CoelacanthBold.otf"
  font "CoelacanthCaption.otf"
  font "CoelacanthCaptionBold.otf"
  font "CoelacanthCaptionExtraLt.otf"
  font "CoelacanthCaptionHeavy.otf"
  font "CoelacanthCaptionLt.otf"
  font "CoelacanthCaptionSemibd.otf"
  font "CoelacanthDisplay.otf"
  font "CoelacanthDisplayBold.otf"
  font "CoelacanthDisplayExtraLt.otf"
  font "CoelacanthDisplayHeavy.otf"
  font "CoelacanthDisplayLt.otf"
  font "CoelacanthDisplaySemibd.otf"
  font "CoelacanthExtraLt.otf"
  font "CoelacanthHeavy.otf"
  font "CoelacanthItalic.otf"
  font "CoelacanthLt.otf"
  font "CoelacanthPearl.otf"
  font "CoelacanthPearlBold.otf"
  font "CoelacanthPearlExtraLt.otf"
  font "CoelacanthPearlHeavy.otf"
  font "CoelacanthPearlLt.otf"
  font "CoelacanthPearlSemibd.otf"
  font "CoelacanthSemibd.otf"
  font "CoelacanthSubcapt.otf"
  font "CoelacanthSubcaptBold.otf"
  font "CoelacanthSubcaptExtraLt.otf"
  font "CoelacanthSubcaptHeavy.otf"
  font "CoelacanthSubcaptLt.otf"
  font "CoelacanthSubcaptSemibd.otf"
  font "CoelacanthSubhd.otf"
  font "CoelacanthSubhdBold.otf"
  font "CoelacanthSubhdExtraLt.otf"
  font "CoelacanthSubhdHeavy.otf"
  font "CoelacanthSubhdLt.otf"
  font "CoelacanthSubhdSemibd.otf"
end
