cask "font-mplus-nerd-font" do
  version "2.3.3"
  sha256 "0a984e487cfb412a8038c73efbe84459f5eeed1e7cedb0dd19c10ccd36d975d3"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/MPlus.zip"
  name "Mplus Nerd Font (M+)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "M+ 1c Nerd Font Complete.ttf"
  font "M+ 1c black Nerd Font Complete.ttf"
  font "M+ 1c bold Nerd Font Complete.ttf"
  font "M+ 1c heavy Nerd Font Complete.ttf"
  font "M+ 1c light Nerd Font Complete.ttf"
  font "M+ 1c medium Nerd Font Complete.ttf"
  font "M+ 1c thin Nerd Font Complete.ttf"
  font "M+ 1m Nerd Font Complete Mono.ttf"
  font "M+ 1m Nerd Font Complete.ttf"
  font "M+ 1m bold Nerd Font Complete Mono.ttf"
  font "M+ 1m bold Nerd Font Complete.ttf"
  font "M+ 1m light Nerd Font Complete Mono.ttf"
  font "M+ 1m light Nerd Font Complete.ttf"
  font "M+ 1m medium Nerd Font Complete Mono.ttf"
  font "M+ 1m medium Nerd Font Complete.ttf"
  font "M+ 1m thin Nerd Font Complete Mono.ttf"
  font "M+ 1m thin Nerd Font Complete.ttf"
  font "M+ 1mn Nerd Font Complete Mono.ttf"
  font "M+ 1mn Nerd Font Complete.ttf"
  font "M+ 1mn bold Nerd Font Complete Mono.ttf"
  font "M+ 1mn bold Nerd Font Complete.ttf"
  font "M+ 1mn light Nerd Font Complete Mono.ttf"
  font "M+ 1mn light Nerd Font Complete.ttf"
  font "M+ 1mn medium Nerd Font Complete Mono.ttf"
  font "M+ 1mn medium Nerd Font Complete.ttf"
  font "M+ 1mn thin Nerd Font Complete Mono.ttf"
  font "M+ 1mn thin Nerd Font Complete.ttf"
  font "M+ 1p Nerd Font Complete.ttf"
  font "M+ 1p black Nerd Font Complete.ttf"
  font "M+ 1p bold Nerd Font Complete.ttf"
  font "M+ 1p heavy Nerd Font Complete.ttf"
  font "M+ 1p light Nerd Font Complete.ttf"
  font "M+ 1p medium Nerd Font Complete.ttf"
  font "M+ 1p thin Nerd Font Complete.ttf"
  font "M+ 2c Nerd Font Complete.ttf"
  font "M+ 2c black Nerd Font Complete.ttf"
  font "M+ 2c bold Nerd Font Complete.ttf"
  font "M+ 2c heavy Nerd Font Complete.ttf"
  font "M+ 2c light Nerd Font Complete.ttf"
  font "M+ 2c medium Nerd Font Complete.ttf"
  font "M+ 2c thin Nerd Font Complete.ttf"
  font "M+ 2m Nerd Font Complete Mono.ttf"
  font "M+ 2m Nerd Font Complete.ttf"
  font "M+ 2m bold Nerd Font Complete Mono.ttf"
  font "M+ 2m bold Nerd Font Complete.ttf"
  font "M+ 2m light Nerd Font Complete Mono.ttf"
  font "M+ 2m light Nerd Font Complete.ttf"
  font "M+ 2m medium Nerd Font Complete Mono.ttf"
  font "M+ 2m medium Nerd Font Complete.ttf"
  font "M+ 2m thin Nerd Font Complete Mono.ttf"
  font "M+ 2m thin Nerd Font Complete.ttf"
  font "M+ 2p Nerd Font Complete.ttf"
  font "M+ 2p black Nerd Font Complete.ttf"
  font "M+ 2p bold Nerd Font Complete.ttf"
  font "M+ 2p heavy Nerd Font Complete.ttf"
  font "M+ 2p light Nerd Font Complete.ttf"
  font "M+ 2p medium Nerd Font Complete.ttf"
  font "M+ 2p thin Nerd Font Complete.ttf"
end
