cask "font-coelacanth" do
  version "0.008"
  sha256 "e3fd1bec5f2daf9c4cadd53012be98d7862965d4385464c022400448dcf8acb9"

  url "https://github.com/Fuzzypeg/Coelacanth/blob/master/release/coelacanth_v#{version}.zip"
  name "Coelacanth"
  desc "Serif typeface inspired by Bruce Rogers' Centaur"
  homepage "https://github.com/Fuzzypeg/Coelacanth"

  font "Coelacanth.otf"
  font "CoelacanthBold.otf"
  font "CoelacanthCaption.otf"
  font "CoelacanthCaptionBold.otf"
  font "CoelacanthCaptionExtraLt.otf"
  font "CoelacanthCaptionHeavy.otf"
  font "CoelacanthCaptionLt.otf"
  font "CoelacanthCaptionSemibd.otf"
  font "CoelacanthDisplay.otf"
  font "CoelacanthDisplayBold.otf"
  font "CoelacanthDisplayExtraLt.otf"
  font "CoelacanthDisplayHeavy.otf"
  font "CoelacanthDisplayLt.otf"
  font "CoelacanthDisplaySemibd.otf"
  font "CoelacanthExtraLt.otf"
  font "CoelacanthHeavy.otf"
  font "CoelacanthItalic.otf"
  font "CoelacanthLt.otf"
  font "CoelacanthPearl.otf"
  font "CoelacanthPearlBold.otf"
  font "CoelacanthPearlExtraLt.otf"
  font "CoelacanthPearlHeavy.otf"
  font "CoelacanthPearlLt.otf"
  font "CoelacanthPearlSemibd.otf"
  font "CoelacanthSemibd.otf"
  font "CoelacanthSubcapt.otf"
  font "CoelacanthSubcaptBold.otf"
  font "CoelacanthSubcaptExtraLt.otf"
  font "CoelacanthSubcaptHeavy.otf"
  font "CoelacanthSubcaptLt.otf"
  font "CoelacanthSubcaptSemibd.otf"
  font "CoelacanthSubhd.otf"
  font "CoelacanthSubhdBold.otf"
  font "CoelacanthSubhdExtraLt.otf"
  font "CoelacanthSubhdHeavy.otf"
  font "CoelacanthSubhdLt.otf"
  font "CoelacanthSubhdSemibd.otf"
end
