# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-quattrocento-sans' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Quattrocento Sans'
  homepage 'https://fonts.google.com/specimen/Quattrocento+Sans'

  font 'ofl/quattrocentosans/QuattrocentoSans-Bold.ttf'
  font 'ofl/quattrocentosans/QuattrocentoSans-BoldItalic.ttf'
  font 'ofl/quattrocentosans/QuattrocentoSans-Italic.ttf'
  font 'ofl/quattrocentosans/QuattrocentoSans-Regular.ttf'
end
