# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-big-shoulders-text' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Big Shoulders Text'
  homepage 'https://fonts.google.com/specimen/Big+Shoulders+Text'

  font 'ofl/bigshoulderstext/BigShouldersText-Black.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-Bold.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-ExtraBold.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-Light.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-Medium.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-Regular.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-SemiBold.ttf'
  font 'ofl/bigshoulderstext/BigShouldersText-Thin.ttf'
end
