# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-puritan' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Puritan'
  homepage 'https://fonts.google.com/specimen/Puritan'

  font 'ofl/puritan/Puritan-Bold.ttf'
  font 'ofl/puritan/Puritan-BoldItalic.ttf'
  font 'ofl/puritan/Puritan-Italic.ttf'
  font 'ofl/puritan/Puritan-Regular.ttf'
end
