# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-bellota' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Bellota'
  homepage 'https://fonts.google.com/specimen/Bellota'

  font 'ofl/bellota/Bellota-Bold.ttf'
  font 'ofl/bellota/Bellota-BoldItalic.ttf'
  font 'ofl/bellota/Bellota-Italic.ttf'
  font 'ofl/bellota/Bellota-Light.ttf'
  font 'ofl/bellota/Bellota-LightItalic.ttf'
  font 'ofl/bellota/Bellota-Regular.ttf'
end
