# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-merienda' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Merienda'
  homepage 'https://fonts.google.com/specimen/Merienda'

  font 'ofl/merienda/Merienda-Bold.ttf'
  font 'ofl/merienda/Merienda-Regular.ttf'
end
