# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-ponnala' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/ponnala/Ponnala-Regular.ttf'
  name 'Ponnala'
  homepage 'https://fonts.google.com/specimen/Ponnala'

  font 'Ponnala-Regular.ttf'
end
