# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-economica' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Economica'
  homepage 'https://fonts.google.com/specimen/Economica'

  font 'ofl/economica/Economica-Bold.ttf'
  font 'ofl/economica/Economica-BoldItalic.ttf'
  font 'ofl/economica/Economica-Italic.ttf'
  font 'ofl/economica/Economica-Regular.ttf'
end
