cask "font-jetbrains-mono-nerd-font" do
  version "3.0.0"
  sha256 "ccaa9c2625a20b47bc253ccd1d59a6f726cee8922d5b9b52c197364d36e9eeeb"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/JetBrainsMono.zip"
  name "JetBrainsMono Nerd Font families (JetBrains Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "JetBrains Mono Bold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Bold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Bold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Bold Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraBold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono ExtraBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraBold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono ExtraBold Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraLight Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono ExtraLight Italic Nerd Font Complete.ttf"
  font "JetBrains Mono ExtraLight Nerd Font Complete Mono.ttf"
  font "JetBrains Mono ExtraLight Nerd Font Complete.ttf"
  font "JetBrains Mono Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Light Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Light Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Light Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Light Nerd Font Complete.ttf"
  font "JetBrains Mono Medium Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Medium Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Medium Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Medium Nerd Font Complete.ttf"
  font "JetBrains Mono NL Bold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Bold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL Bold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Bold Nerd Font Complete.ttf"
  font "JetBrains Mono NL ExtraBold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL ExtraBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL ExtraBold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL ExtraBold Nerd Font Complete.ttf"
  font "JetBrains Mono NL ExtraLight Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL ExtraLight Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL ExtraLight Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL ExtraLight Nerd Font Complete.ttf"
  font "JetBrains Mono NL Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL Light Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Light Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL Light Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Light Nerd Font Complete.ttf"
  font "JetBrains Mono NL Medium Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Medium Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL Medium Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Medium Nerd Font Complete.ttf"
  font "JetBrains Mono NL Regular Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Regular Nerd Font Complete.ttf"
  font "JetBrains Mono NL SemiBold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL SemiBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL SemiBold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL SemiBold Nerd Font Complete.ttf"
  font "JetBrains Mono NL Thin Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Thin Italic Nerd Font Complete.ttf"
  font "JetBrains Mono NL Thin Nerd Font Complete Mono.ttf"
  font "JetBrains Mono NL Thin Nerd Font Complete.ttf"
  font "JetBrains Mono Regular Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Regular Nerd Font Complete.ttf"
  font "JetBrains Mono SemiBold Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono SemiBold Italic Nerd Font Complete.ttf"
  font "JetBrains Mono SemiBold Nerd Font Complete Mono.ttf"
  font "JetBrains Mono SemiBold Nerd Font Complete.ttf"
  font "JetBrains Mono Thin Italic Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Thin Italic Nerd Font Complete.ttf"
  font "JetBrains Mono Thin Nerd Font Complete Mono.ttf"
  font "JetBrains Mono Thin Nerd Font Complete.ttf"
end
