# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-hind-jalandhar' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Hind Jalandhar'
  homepage 'https://fonts.google.com/specimen/Hind+Jalandhar'

  font 'ofl/hindjalandhar/HindJalandhar-Bold.ttf'
  font 'ofl/hindjalandhar/HindJalandhar-Light.ttf'
  font 'ofl/hindjalandhar/HindJalandhar-Medium.ttf'
  font 'ofl/hindjalandhar/HindJalandhar-Regular.ttf'
  font 'ofl/hindjalandhar/HindJalandhar-SemiBold.ttf'
end
