cask "font-martian-mono" do
  version "0.9.0"
  sha256 :no_check

  name "Martian Mono"
  url "https://github.com/evilmartians/mono/releases/download/v#{version}/martian-mono-#{version}-otf.zip"
  homepage "https://github.com/evilmartians/mono"

  font "MartianMono-CnBd.otf"
  font "MartianMono-CnLt.otf"
  font "MartianMono-CnMd.otf"
  font "MartianMono-CnRg.otf"
  font "MartianMono-CnTh.otf"
  font "MartianMono-CnxBd.otf"
  font "MartianMono-CnxLt.otf"
  font "MartianMono-NrBd.otf"
  font "MartianMono-NrLt.otf"
  font "MartianMono-NrMd.otf"
  font "MartianMono-NrRg.otf"
  font "MartianMono-NrTh.otf"
  font "MartianMono-NrxBd.otf"
  font "MartianMono-NrxLt.otf"
  font "MartianMono-StdBd.otf"
  font "MartianMono-StdLt.otf"
  font "MartianMono-StdMd.otf"
  font "MartianMono-StdRg.otf"
  font "MartianMono-StdTh.otf"
  font "MartianMono-StdxBd.otf"
  font "MartianMono-StdxLt.otf"
  font "MartianMono-WdBd.otf"
  font "MartianMono-WdLt.otf"
  font "MartianMono-WdMd.otf"
  font "MartianMono-WdRg.otf"
  font "MartianMono-WdTh.otf"
  font "MartianMono-WdxBd.otf"
  font "MartianMono-WdxLt.otf"
end
