# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-fira-sans-extra-condensed' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Fira Sans Extra Condensed'
  homepage 'https://fonts.google.com/specimen/Fira+Sans+Extra+Condensed'

  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Black.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-BlackItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Bold.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-BoldItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-ExtraBold.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-ExtraBoldItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-ExtraLight.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-ExtraLightItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Italic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Light.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-LightItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Medium.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-MediumItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Regular.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-SemiBold.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-SemiBoldItalic.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-Thin.ttf'
  font 'ofl/firasansextracondensed/FiraSansExtraCondensed-ThinItalic.ttf'
end
