class FontUbuntu < Cask
  url 'http://font.ubuntu.com/download/ubuntu-font-family-0.80.zip'
  homepage 'http://font.ubuntu.com/'
  version '0.80'
  sha1 '88276ba9d38d75b33a9640efa15cd80979cb21e2'
  font 'ubuntu-font-family-0.80/Ubuntu-B.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-BI.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-C.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-L.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-LI.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-M.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-MI.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-R.ttf'
  font 'ubuntu-font-family-0.80/Ubuntu-RI.ttf'
  font 'ubuntu-font-family-0.80/UbuntuMono-B.ttf'
  font 'ubuntu-font-family-0.80/UbuntuMono-BI.ttf'
  font 'ubuntu-font-family-0.80/UbuntuMono-R.ttf'
  font 'ubuntu-font-family-0.80/UbuntuMono-RI.ttf'
end
