# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-baumans' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/baumans/Baumans-Regular.ttf'
  name 'Baumans'
  homepage 'https://fonts.google.com/specimen/Baumans'

  font 'Baumans-Regular.ttf'
end
