# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-asul' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Asul'
  homepage 'https://fonts.google.com/specimen/Asul'

  font 'ofl/asul/Asul-Bold.ttf'
  font 'ofl/asul/Asul-Regular.ttf'
end
