# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-corben' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Corben'
  homepage 'https://fonts.google.com/specimen/Corben'

  font 'ofl/corben/Corben-Bold.ttf'
  font 'ofl/corben/Corben-Regular.ttf'
end
