cask "font-meslo-lg-nerd-font" do
  version "2.2.1"
  sha256 "fa206721add4716ff6437fc2ea6e5b65c9dad8d5565117f80f13df7dd1261f98"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Meslo.zip"
  name "MesloLG Nerd Font families (Meslo LG)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  font "Meslo LG M Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG M Bold Nerd Font Complete.ttf"
  font "Meslo LG M Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG M Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG M Regular Nerd Font Complete.ttf"
  font "Meslo LG M Italic Nerd Font Complete.ttf"
  font "Meslo LG M Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Nerd Font Complete.ttf"
  font "Meslo LG L Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG L Regular Nerd Font Complete.ttf"
  font "Meslo LG L Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG L Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Italic Nerd Font Complete.ttf"
  font "Meslo LG S Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG S Bold Nerd Font Complete.ttf"
  font "Meslo LG S Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG S Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S Regular Nerd Font Complete.ttf"
  font "Meslo LG S Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG S Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S Italic Nerd Font Complete.ttf"
  font "Meslo LG L DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG L DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG L DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG L DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Italic Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG M DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Italic Nerd Font Complete.ttf"
  font "Meslo LG S DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG S DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG S DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG S DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Italic Nerd Font Complete.ttf"
end
