cask 'font-powerline' do
  version '2015-12-04'
  sha256 'b6673e0e28441cc04065f8e5c79960aeaa220dae52351852b37e6cf3a03bb8af'

  url "https://github.com/powerline/fonts/archive/#{version}.zip"
  appcast 'https://github.com/powerline/fonts/releases.atom'
  name 'Fonts for Powerline'
  homepage 'https://github.com/powerline/fonts/'

  font "fonts-#{version}/AnonymousPro/Anonymice Powerline Bold Italic.ttf"
  font "fonts-#{version}/AnonymousPro/Anonymice Powerline Bold.ttf"
  font "fonts-#{version}/AnonymousPro/Anonymice Powerline Italic.ttf"
  font "fonts-#{version}/AnonymousPro/Anonymice Powerline.ttf"
  font "fonts-#{version}/Arimo/Arimo Bold Italic for Powerline.ttf"
  font "fonts-#{version}/Arimo/Arimo Bold for Powerline.ttf"
  font "fonts-#{version}/Arimo/Arimo Italic for Powerline.ttf"
  font "fonts-#{version}/Arimo/Arimo for Powerline.ttf"
  font "fonts-#{version}/Cousine/Cousine Bold Italic for Powerline.ttf"
  font "fonts-#{version}/Cousine/Cousine Bold for Powerline.ttf"
  font "fonts-#{version}/Cousine/Cousine Italic for Powerline.ttf"
  font "fonts-#{version}/Cousine/Cousine for Powerline.ttf"
  font "fonts-#{version}/DejaVuSansMono/DejaVu Sans Mono Bold Oblique for Powerline.ttf"
  font "fonts-#{version}/DejaVuSansMono/DejaVu Sans Mono Bold for Powerline.ttf"
  font "fonts-#{version}/DejaVuSansMono/DejaVu Sans Mono Oblique for Powerline.ttf"
  font "fonts-#{version}/DejaVuSansMono/DejaVu Sans Mono for Powerline.ttf"
  font "fonts-#{version}/DroidSansMono/Droid Sans Mono for Powerline.otf"
  font "fonts-#{version}/DroidSansMonoDotted/Droid Sans Mono Dotted for Powerline.ttf"
  font "fonts-#{version}/DroidSansMonoSlashed/Droid Sans Mono Slashed for Powerline.ttf"
  font "fonts-#{version}/FiraMono/FuraMono-Bold Powerline.otf"
  font "fonts-#{version}/FiraMono/FuraMono-Medium Powerline.otf"
  font "fonts-#{version}/FiraMono/FuraMono-Regular Powerline.otf"
  font "fonts-#{version}/Hack/Hack-Bold.ttf"
  font "fonts-#{version}/Hack/Hack-BoldItalic.ttf"
  font "fonts-#{version}/Hack/Hack-Italic.ttf"
  font "fonts-#{version}/Hack/Hack-Regular.ttf"
  font "fonts-#{version}/Inconsolata-g/Inconsolata-g for Powerline.otf"
  font "fonts-#{version}/Inconsolata/Inconsolata for Powerline.otf"
  font "fonts-#{version}/InconsolataDz/Inconsolata-dz for Powerline.otf"
  font "fonts-#{version}/LiberationMono/Literation Mono Powerline Bold Italic.ttf"
  font "fonts-#{version}/LiberationMono/Literation Mono Powerline Bold.ttf"
  font "fonts-#{version}/LiberationMono/Literation Mono Powerline Italic.ttf"
  font "fonts-#{version}/LiberationMono/Literation Mono Powerline.ttf"
  font "fonts-#{version}/Meslo/Meslo LG L DZ Regular for Powerline.otf"
  font "fonts-#{version}/Meslo/Meslo LG L Regular for Powerline.otf"
  font "fonts-#{version}/Meslo/Meslo LG M DZ Regular for Powerline.otf"
  font "fonts-#{version}/Meslo/Meslo LG M Regular for Powerline.otf"
  font "fonts-#{version}/Meslo/Meslo LG S DZ Regular for Powerline.otf"
  font "fonts-#{version}/Meslo/Meslo LG S Regular for Powerline.otf"
  font "fonts-#{version}/Monofur/Monofur Bold for Powerline.ttf"
  font "fonts-#{version}/Monofur/Monofur Italic for Powerline.ttf"
  font "fonts-#{version}/Monofur/Monofur for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Bold Italic for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Bold for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Italic for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Light Italic for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Light for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Medium Italic for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Medium for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Thin Italic for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono Thin for Powerline.ttf"
  font "fonts-#{version}/RobotoMono/Roboto Mono for Powerline.ttf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Black.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Bold.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline ExtraLight.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Light.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Medium.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Regular.otf"
  font "fonts-#{version}/SourceCodePro/Sauce Code Powerline Semibold.otf"
  font "fonts-#{version}/SymbolNeu/Symbol Neu for Powerline.ttf"
  font "fonts-#{version}/Tinos/Tinos Bold Italic for Powerline.ttf"
  font "fonts-#{version}/Tinos/Tinos Bold for Powerline.ttf"
  font "fonts-#{version}/Tinos/Tinos Italic for Powerline.ttf"
  font "fonts-#{version}/Tinos/Tinos for Powerline.ttf"
  font "fonts-#{version}/UbuntuMono/Ubuntu Mono derivative Powerline Bold Italic.ttf"
  font "fonts-#{version}/UbuntuMono/Ubuntu Mono derivative Powerline Bold.ttf"
  font "fonts-#{version}/UbuntuMono/Ubuntu Mono derivative Powerline Italic.ttf"
  font "fonts-#{version}/UbuntuMono/Ubuntu Mono derivative Powerline.ttf"
end
