# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-im-fell-double-pica' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'IM Fell Double Pica'
  homepage 'https://fonts.google.com/specimen/IM+Fell+Double+Pica'

  font 'ofl/imfelldoublepica/IMFELLDoublePica-Italic.ttf'
  font 'ofl/imfelldoublepica/IMFELLDoublePica-Regular.ttf'
end
