# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-girassol' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/girassol/Girassol-Regular.ttf'
  name 'Girassol'
  homepage 'https://fonts.google.com/specimen/Girassol'

  font 'Girassol-Regular.ttf'
end
