# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-roboto-mono' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Roboto Mono'
  homepage 'https://fonts.google.com/specimen/Roboto+Mono'

  font 'apache/robotomono/RobotoMono-Italic[wght].ttf'
  font 'apache/robotomono/RobotoMono[wght].ttf'
end
