# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-pragati-narrow' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Pragati Narrow'
  homepage 'https://fonts.google.com/specimen/Pragati+Narrow'

  font 'ofl/pragatinarrow/PragatiNarrow-Bold.ttf'
  font 'ofl/pragatinarrow/PragatiNarrow-Regular.ttf'
end
