cask "font-urbanist" do
  version "1.251"
  sha256 "653b0298e14c0ee6a530b466e2af88b88a1b829edbdaf0e6500efcd4561fd1d0"

  url "https://github.com/coreywho/Urbanist/releases/download/#{version}/Urbanist_Font_Family_#{version}.zip"
  appcast "https://github.com/coreywho/Urbanist/releases.atom"
  name "Urbanist"
  homepage "https://github.com/coreywho/Urbanist"

  font "fonts/variable/Urbanist[ital,wght].ttf"
  font "fonts/otf/Urbanist-Black.otf"
  font "fonts/otf/Urbanist-BlackItalic.otf"
  font "fonts/otf/Urbanist-Bold.otf"
  font "fonts/otf/Urbanist-BoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraBold.otf"
  font "fonts/otf/Urbanist-ExtraBoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraLight.otf"
  font "fonts/otf/Urbanist-ExtraLightItalic.otf"
  font "fonts/otf/Urbanist-Italic.otf"
  font "fonts/otf/Urbanist-Light.otf"
  font "fonts/otf/Urbanist-LightItalic.otf"
  font "fonts/otf/Urbanist-Medium.otf"
  font "fonts/otf/Urbanist-MediumItalic.otf"
  font "fonts/otf/Urbanist-Regular.otf"
  font "fonts/otf/Urbanist-SemiBold.otf"
  font "fonts/otf/Urbanist-SemiBoldItalic.otf"
  font "fonts/otf/Urbanist-Thin.otf"
  font "fonts/otf/Urbanist-ThinItalic.otf"
end
