# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-libre-baskerville' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Libre Baskerville'
  homepage 'https://fonts.google.com/specimen/Libre+Baskerville'

  font 'ofl/librebaskerville/LibreBaskerville-Bold.ttf'
  font 'ofl/librebaskerville/LibreBaskerville-Italic.ttf'
  font 'ofl/librebaskerville/LibreBaskerville-Regular.ttf'
end
