# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-baloo-2' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Baloo 2'
  homepage 'https://fonts.google.com/specimen/Baloo+2'

  font 'ofl/baloo2/Baloo2-Bold.ttf'
  font 'ofl/baloo2/Baloo2-ExtraBold.ttf'
  font 'ofl/baloo2/Baloo2-Medium.ttf'
  font 'ofl/baloo2/Baloo2-Regular.ttf'
  font 'ofl/baloo2/Baloo2-SemiBold.ttf'
end
