# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-tajawal' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Tajawal'
  homepage 'https://fonts.google.com/specimen/Tajawal'

  font 'ofl/tajawal/Tajawal-Black.ttf'
  font 'ofl/tajawal/Tajawal-Bold.ttf'
  font 'ofl/tajawal/Tajawal-ExtraBold.ttf'
  font 'ofl/tajawal/Tajawal-ExtraLight.ttf'
  font 'ofl/tajawal/Tajawal-Light.ttf'
  font 'ofl/tajawal/Tajawal-Medium.ttf'
  font 'ofl/tajawal/Tajawal-Regular.ttf'
end
