cask "font-urbanist" do
  version "1.300"
  sha256 "cd9e045dd2bfab1aded56abf58efbeda87868829c3df89f1baac48211fe0443e"

  url "https://github.com/coreywho/Urbanist/releases/download/#{version}/Urbanist_Font_Family_#{version}.zip"
  name "Urbanist"
  homepage "https://github.com/coreywho/Urbanist"

  font "fonts/variable/Urbanist[ital,wght].ttf"
  font "fonts/otf/Urbanist-Black.otf"
  font "fonts/otf/Urbanist-BlackItalic.otf"
  font "fonts/otf/Urbanist-Bold.otf"
  font "fonts/otf/Urbanist-BoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraBold.otf"
  font "fonts/otf/Urbanist-ExtraBoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraLight.otf"
  font "fonts/otf/Urbanist-ExtraLightItalic.otf"
  font "fonts/otf/Urbanist-Italic.otf"
  font "fonts/otf/Urbanist-Light.otf"
  font "fonts/otf/Urbanist-LightItalic.otf"
  font "fonts/otf/Urbanist-Medium.otf"
  font "fonts/otf/Urbanist-MediumItalic.otf"
  font "fonts/otf/Urbanist-Regular.otf"
  font "fonts/otf/Urbanist-SemiBold.otf"
  font "fonts/otf/Urbanist-SemiBoldItalic.otf"
  font "fonts/otf/Urbanist-Thin.otf"
  font "fonts/otf/Urbanist-ThinItalic.otf"
end
