cask 'font-noto-serif-georgian' do
  version :latest
  sha256 :no_check

  # noto-website-2.storage.googleapis.com was verified as official when first introduced to the cask
  url 'https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifGeorgian-unhinted.zip'
  name 'Noto Serif Georgian'
  homepage 'https://www.google.com/get/noto/#serif-geor'

  font 'NotoSerifGeorgian-Black.ttf'
  font 'NotoSerifGeorgian-Bold.ttf'
  font 'NotoSerifGeorgian-Condensed.ttf'
  font 'NotoSerifGeorgian-CondensedBlack.ttf'
  font 'NotoSerifGeorgian-CondensedBold.ttf'
  font 'NotoSerifGeorgian-CondensedExtraBold.ttf'
  font 'NotoSerifGeorgian-CondensedExtraLight.ttf'
  font 'NotoSerifGeorgian-CondensedLight.ttf'
  font 'NotoSerifGeorgian-CondensedMedium.ttf'
  font 'NotoSerifGeorgian-CondensedSemiBold.ttf'
  font 'NotoSerifGeorgian-CondensedThin.ttf'
  font 'NotoSerifGeorgian-ExtraBold.ttf'
  font 'NotoSerifGeorgian-ExtraCondensed.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedBlack.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedBold.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedExtraBold.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedExtraLight.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedLight.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedMedium.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedSemiBold.ttf'
  font 'NotoSerifGeorgian-ExtraCondensedThin.ttf'
  font 'NotoSerifGeorgian-ExtraLight.ttf'
  font 'NotoSerifGeorgian-Light.ttf'
  font 'NotoSerifGeorgian-Medium.ttf'
  font 'NotoSerifGeorgian-Regular.ttf'
  font 'NotoSerifGeorgian-SemiBold.ttf'
  font 'NotoSerifGeorgian-SemiCondensed.ttf'
  font 'NotoSerifGeorgian-SemiCondensedBlack.ttf'
  font 'NotoSerifGeorgian-SemiCondensedBold.ttf'
  font 'NotoSerifGeorgian-SemiCondensedExtraBold.ttf'
  font 'NotoSerifGeorgian-SemiCondensedExtraLight.ttf'
  font 'NotoSerifGeorgian-SemiCondensedLight.ttf'
  font 'NotoSerifGeorgian-SemiCondensedMedium.ttf'
  font 'NotoSerifGeorgian-SemiCondensedSemiBold.ttf'
  font 'NotoSerifGeorgian-SemiCondensedThin.ttf'
  font 'NotoSerifGeorgian-Thin.ttf'
end
