cask "font-libertinus" do
  version "7.010"
  sha256 "d7b9cd1a1e56d11721db2093a09e96972420e03a5662394f81a793ee6998c746"

  url "https://github.com/alerque/libertinus/releases/download/v#{version}/Libertinus-#{version}.tar.xz"
  appcast "https://github.com/alif-type/libertinus/releases.atom"
  name "Libertinus"
  desc "Proportional serif typeface inspired by 19th century book type"
  homepage "https://github.com/alif-type/libertinus"

  font "Libertinus-#{version}/static/OTF/LibertinusKeyboard-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusMath-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusMono-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Bold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Italic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Bold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-BoldItalic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Italic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Semibold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-SemiboldItalic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerifDisplay-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerifInitials-Regular.otf"
end
