# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-lora' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Lora'
  homepage 'https://fonts.google.com/specimen/Lora'

  font 'ofl/lora/Lora-Italic[wght].ttf'
  font 'ofl/lora/Lora[wght].ttf'
end
