# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-charmonman' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Charmonman'
  homepage 'https://fonts.google.com/specimen/Charmonman'

  font 'ofl/charmonman/Charmonman-Bold.ttf'
  font 'ofl/charmonman/Charmonman-Regular.ttf'
end
