# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-abhaya-libre' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Abhaya Libre'
  homepage 'https://fonts.google.com/specimen/Abhaya+Libre'

  font 'ofl/abhayalibre/AbhayaLibre-Bold.ttf'
  font 'ofl/abhayalibre/AbhayaLibre-ExtraBold.ttf'
  font 'ofl/abhayalibre/AbhayaLibre-Medium.ttf'
  font 'ofl/abhayalibre/AbhayaLibre-Regular.ttf'
  font 'ofl/abhayalibre/AbhayaLibre-SemiBold.ttf'
end
