# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-unna' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Unna'
  homepage 'https://fonts.google.com/specimen/Unna'

  font 'ofl/unna/Unna-Bold.ttf'
  font 'ofl/unna/Unna-BoldItalic.ttf'
  font 'ofl/unna/Unna-Italic.ttf'
  font 'ofl/unna/Unna-Regular.ttf'
end
