cask "font-plemol-jp-nfj" do
  version "1.3.0"
  sha256 "750e9db9ca227f2deabaf93efa4e2ee3bc07c469f8c5e5bae56d335874bb427c"

  url "https://github.com/yuru7/PlemolJP/releases/download/v#{version}/PlemolJP_NFJ_v#{version}.zip"
  name "PlemolJP NF"
  desc "Japanese programming font synthesized from IBM Plex Mono and IBM Plex Sans JP"
  homepage "https://github.com/yuru7/PlemolJP"

  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Bold.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-BoldItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ExtraLight.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ExtraLightItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Italic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Light.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-LightItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Medium.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-MediumItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Regular.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-SemiBold.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-SemiBoldItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Text.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-TextItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Thin.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ThinItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Bold.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-BoldItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ExtraLight.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ExtraLightItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Italic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Light.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-LightItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Medium.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-MediumItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Regular.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-SemiBold.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-SemiBoldItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Text.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-TextItalic.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Thin.ttf"
  font "PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ThinItalic.ttf"
end
