# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-ofl-sorts-mill-goudy-tt' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'OFL Sorts Mill Goudy TT'
  homepage 'https://fonts.google.com/specimen/OFL+Sorts+Mill+Goudy+TT'

  font 'ofl/oflsortsmillgoudytt/OFLGoudyStMTT-Italic.ttf'
  font 'ofl/oflsortsmillgoudytt/OFLGoudyStMTT.ttf'
end
