# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-pacifico' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/pacifico/Pacifico-Regular.ttf'
  name 'Pacifico'
  homepage 'https://fonts.google.com/specimen/Pacifico'

  font 'Pacifico-Regular.ttf'
end
