cask "font-437-plus" do
  version "2.0"
  sha256 "e2130bc9de9d2362275e4cb9cbd927bc0cc3dd10c14a2c5a661ae32cd5d585aa"

  url "https://int10h.org/oldschool-pc-fonts/download/oldschool_pc_font_pack_v#{version}_FULL.zip"
  name "Ac437"
  name "AcPlus"
  name "Mx437"
  name "MxPlus"
  name "Px437"
  name "PxPlus"
  name "Ultimate Oldschool PC Font Pack"
  desc "Collection of classic text mode fonts from DOS-era IBM PCs and compatibles"
  homepage "https://int10h.org/oldschool-pc-fonts/"

  conflicts_with cask: "font-px437-pxplus"

  font "ttf - Px (pixel outline)/PxPlus_AST_PremiumExec.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model30r0.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_CGAthin.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-II_225L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_JPN16.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-II_225L.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_8x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_AMI_EGA_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_MBytePC230_CGA.ttf"
  font "ttf - Px (pixel outline)/Px437_Paradise132_7x9.ttf"
  font "ttf - Px (pixel outline)/Px437_Nix8810_M16.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Tandy1K-II_200L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_TWN19.ttf"
  font "ttf - Px (pixel outline)/Px437_SperryPC_CGA.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Amstrad_PC.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_BIOS-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Amstrad_PC-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DG_One-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Mindset-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_ITT_Xtra-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Mindset.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Amstrad_PC-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Acer710_CGA.ttf"
  font "ttf - Px (pixel outline)/Px437_Nix8810_M15.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_9x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Mindset-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_FMTowns_re_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_ATT_PC6300.ttf"
  font "ttf - Px (pixel outline)/Px437_MBytePC230_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_PRC16.ttf"
  font "ttf - Px (pixel outline)/Px437_MBytePC230_EGA.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Cordata_PPC-21.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_8x8-2x.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_MDA.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_9x8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_XGA-AI_12x23.ttf"
  font "ttf - Px (pixel outline)/Px437_SanyoMBC16.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaTxL1_8x8.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Wyse700a.ttf"
  font "ttf - Px (pixel outline)/Px437_ApricotXenC.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_DOS_ISO8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_DTK_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Amstrad_PC.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_XGA-AI_12x20.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_CGA.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Cordata_PPC-400.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_XGA-AI_12x20.ttf"
  font "ttf - Px (pixel outline)/Px437_Wyse700b-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_ApricotPortable.ttf"
  font "ttf - Px (pixel outline)/Px437_SanyoMBC16-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaT300_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_SmallW_6x8.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Wyse700b.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_JPN12.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_DG_One_Alt-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_9x14-2x.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Tandy1K-II_225L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_DOS_ISO9.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaTxL1_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_SperryPC_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_8x11.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_8x8.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaTxL1_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_PhoenixEGA_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_SeequaCm.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_ANK16.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_CGAthin-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaSat_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-II_200L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_DOS_ISO8.ttf"
  font "ttf - Px (pixel outline)/Px437_CompaqThin_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_PS-55_re.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaSat_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt1-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_EpsonMGA_Alt-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_AST_PremiumExec.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-I_200L.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_RM_Nimbus-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Olivetti_M15-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Tandy1K-II_225L.ttf"
  font "ttf - Px (pixel outline)/Px437_VTech_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_8x14-2x.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_BIOS.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_AMI_EGA_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Paradise132_7x16.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt3-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_AMI_EGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_MDA.ttf"
  font "ttf - Px (pixel outline)/Px437_Olivetti_MxVGA.ttf"
  font "ttf - Px (pixel outline)/Px437_Compaq_Port3-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_PhoenixEGA_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_8x16.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_NEC_APC3_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt1.ttf"
  font "ttf - Px (pixel outline)/Px437_Cordata_PPC-400.ttf"
  font "ttf - Px (pixel outline)/Px437_EpsonMGA_Alt.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Conv.ttf"
  font "ttf - Px (pixel outline)/Px437_Nix8810_M35-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DTK_BIOS.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_PhoenixEGA_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_3270pc.ttf"
  font "ttf - Px (pixel outline)/Px437_RM_Nimbus.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_CGA.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaT300_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt3.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Conv-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_PhoenixEGA_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Philips_YES_T-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Copam_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Conv-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt2.ttf"
  font "ttf - Px (pixel outline)/Px437_ATT_PC6300-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_8x16.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaTxL2_8x8.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_CGAthin-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_NEC_APC3_8x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-II_Mono.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaT300_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_EverexME_5x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Acer710_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_SeequaCm-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Compis.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_8x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Siemens_PC-D.ttf"
  font "ttf - Px (pixel outline)/Px437_LE_Model_D_CGA.ttf"
  font "ttf - Px (pixel outline)/Px437_EverexME_7x8.ttf"
  font "ttf - Px (pixel outline)/Px437_FMTowns_re_8x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_BIOS-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_CGAthin.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Wyse700a-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_PGC-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Olivetti_M15.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Phoenix_BIOS-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_8x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Acer_VGA_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_ANK24.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_ANK30.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-I_200L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_ANK19.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_DOS_ISO9-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_PGC.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_EpsonMGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_LE_Model_D_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_EpsonMGA.ttf"
  font "ttf - Px (pixel outline)/Px437_FMTowns_re_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_LE_Model_D_Mono.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-II_200L.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Apricot_200L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_NEC_APC3_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Philips_YES_G-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_MBytePC230_Mono.ttf"
  font "ttf - Px (pixel outline)/Px437_DG_One.ttf"
  font "ttf - Px (pixel outline)/Px437_VTech_BIOS.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_PRC19.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Phoenix_BIOS.ttf"
  font "ttf - Px (pixel outline)/Px437_EverexME_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model3x_Alt1.ttf"
  font "ttf - Px (pixel outline)/Px437_Kaypro2K_G.ttf"
  font "ttf - Px (pixel outline)/Px437_Apricot_256L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x8.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_8x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy2K-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Apricot_200L.ttf"
  font "ttf - Px (pixel outline)/Px437_Copam_BIOS.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaSat_8x16.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaSat_8x14.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_DG_One_Alt.ttf"
  font "ttf - Px (pixel outline)/Px437_SperryPC_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model3x_Alt2.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x14-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_EpsonMGA_Mono.ttf"
  font "ttf - Px (pixel outline)/Px437_Nix8810_M35.ttf"
  font "ttf - Px (pixel outline)/Px437_Acer_VGA_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Kaypro2K_G-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model3x_Alt3.ttf"
  font "ttf - Px (pixel outline)/Px437_Philips_YES_T.ttf"
  font "ttf - Px (pixel outline)/Px437_ATI_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_BIOS.ttf"
  font "ttf - Px (pixel outline)/PxPlus_Tandy1K-II_200L.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_VGA_9x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_JPN19.ttf"
  font "ttf - Px (pixel outline)/Px437_Philips_YES_G.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-I_225L.ttf"
  font "ttf - Px (pixel outline)/Px437_MBytePC230_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_CompaqThin_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy2K.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_TWN16.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_JPN24.ttf"
  font "ttf - Px (pixel outline)/Px437_ITT_Xtra.ttf"
  font "ttf - Px (pixel outline)/Px437_DOS-V_re_JPN30.ttf"
  font "ttf - Px (pixel outline)/Px437_PhoenixEGA_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_8x8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_EGA_9x8-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_CGA-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Tandy1K-I_225L-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_XGA-AI_7x15.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_EGA_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaTxL2_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_Apricot_256L.ttf"
  font "ttf - Px (pixel outline)/Px437_Trident_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model30r0-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Acer_VGA_9x8.ttf"
  font "ttf - Px (pixel outline)/Px437_NEC_APC3_8x8-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_IBM_Model3x_Alt4.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_9x16.ttf"
  font "ttf - Px (pixel outline)/Px437_Compaq_Port3.ttf"
  font "ttf - Px (pixel outline)/Px437_ToshibaSat_8x8.ttf"
  font "ttf - Px (pixel outline)/Px437_CompaqThin_8x14.ttf"
  font "ttf - Px (pixel outline)/PxPlus_ToshibaTxL2_8x16.ttf"
  font "ttf - Px (pixel outline)/Px437_EagleSpCGA_Alt2-2y.ttf"
  font "ttf - Px (pixel outline)/Px437_Apricot_Mono.ttf"
  font "ttf - Px (pixel outline)/PxPlus_IBM_VGA_8x16-2x.ttf"
  font "ttf - Px (pixel outline)/Px437_Verite_9x14.ttf"
  font "ttf - Px (pixel outline)/Px437_AMI_EGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Conv-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Cordata_PPC-400.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Acer710_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_PGC-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Phoenix_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_PhoenixEGA_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Compaq_Port3-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt1.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaSat_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-II_200L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Apricot_200L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Tandy1K-II_225L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Conv-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaTxL1_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_VTech_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_9x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaTxL2_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt1-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt2.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaSat_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt3.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_PhoenixEGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_LE_Model_D_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_RM_Nimbus.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt3-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_NEC_APC3_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Philips_YES_T-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_ANK19.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_VTech_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaTxL2_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SperryPC_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_ANK30.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_ANK24.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_8x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Apricot_256L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Paradise132_7x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Olivetti_M15-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Acer_VGA_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Compaq_Port3.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATT_PC6300-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_AST_PremiumExec.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaT300_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Copam_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EpsonMGA_Alt-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EpsonMGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Apricot_Mono.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Tandy1K-II_200L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_AMI_EGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-I_225L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Mindset.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-II_225L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaTxL1_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EverexME_5x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_8x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_9x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Compis.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DTK_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DG_One_Alt.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Wyse700b-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_PRC19.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model30r0.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_MDA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_AST_PremiumExec.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Siemens_PC-D.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaT300_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ApricotXenC.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy2K-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EverexME_7x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_8x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Copam_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_CGAthin.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ApricotPortable.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_DOS_ISO8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Kaypro2K_G.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Amstrad_PC-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_JPN30.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ITT_Xtra.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_JPN24.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Olivetti_M15.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Acer710_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Nix8810_M15.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_9x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_8x8-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_LE_Model_D_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Acer_VGA_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Paradise132_7x9.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Cordata_PPC-400.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_XGA-AI_12x20.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ITT_Xtra-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-II_225L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-I_225L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_JPN19.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Amstrad_PC.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_TWN19.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DG_One_Alt-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Nix8810_M16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Tandy1K-II_225L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_9x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_XGA-AI_12x23.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-I_200L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SanyoMBC16-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_CGAthin.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_NEC_APC3_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DG_One.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DG_One-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_AMI_EGA_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_DOS_ISO9.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_PhoenixEGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_XGA-AI_7x15.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaSat_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_8x11.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATT_PC6300.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_PGC.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Mindset-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_CompaqThin_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model3x_Alt2.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model3x_Alt3.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Mindset-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_MBytePC230_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EverexME_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_MBytePC230_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_JPN16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_DOS_ISO8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_TWN16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_FMTowns_re_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_PS-55_re.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Philips_YES_T.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Amstrad_PC-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model3x_Alt1.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Kaypro2K_G-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaTxL1_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_8x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EpsonMGA_Mono.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_CompaqThin_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_RM_Nimbus-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SperryPC_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_ToshibaSat_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_NEC_APC3_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Wyse700a.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_PhoenixEGA_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model30r0-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaTxL2_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_AMI_EGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Model3x_Alt4.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Cordata_PPC-21.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_MDA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Apricot_256L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Amstrad_PC.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Philips_YES_G.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_PRC16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Nix8810_M35.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_MBytePC230_EGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_8x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EpsonMGA_Alt.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_JPN12.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Wyse700b.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_Tandy1K-II_200L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Acer_VGA_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_SmallW_6x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EagleSpCGA_Alt2-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SanyoMBC16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy2K.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_CompaqThin_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SeequaCm.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_PhoenixEGA_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DOS-V_re_ANK16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_DOS_ISO9-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_CGAthin-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_EpsonMGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_8x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_9x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SperryPC_CGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_BIOS-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_MBytePC230_CGA-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Phoenix_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_MBytePC230_Mono.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Verite_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-II_200L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ATI_9x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-I_200L.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_NEC_APC3_8x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_FMTowns_re_8x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Apricot_200L-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaT300_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_LE_Model_D_Mono.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_FMTowns_re_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Trident_9x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Wyse700a-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_Conv.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_BIOS-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_XGA-AI_12x20.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_DTK_BIOS.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Nix8810_M35-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Tandy1K-II_Mono.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Olivetti_MxVGA.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_VGA_9x16-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_3270pc.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_EGA_8x8.ttf"
  font "ttf - Mx (mixed outline+bitmap)/MxPlus_IBM_CGAthin-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_BIOS-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_Philips_YES_G-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_AMI_EGA_8x8-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_SeequaCm-2y.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_EGA_8x14.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_ToshibaSat_8x16.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_8x14-2x.ttf"
  font "ttf - Mx (mixed outline+bitmap)/Mx437_IBM_VGA_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SanyoMBC16-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_AMI_EGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt1-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_NEC_APC3_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DG_One_Alt-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model3x_Alt1.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_CompaqThin_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_8x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EpsonMGA_Alt.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaSat_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x16-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaSat_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_MDA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model3x_Alt2.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_MBytePC230_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_CompaqThin_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model3x_Alt3.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy1K-II_200L-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_PhoenixEGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_3270pc.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_8x11.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_Tandy1K-II_200L.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaT300_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_MDA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_DOS_ISO9.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Amstrad_PC-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Acer_VGA_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_DOS_ISO8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Wyse700a.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaTxL2_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaTxL2_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model30r0-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt3-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Nix8810_M35.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model3x_Alt4.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Model30r0.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_8x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_9x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Wyse700b.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_8x16-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_LE_Model_D_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DG_One.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATT_PC6300-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_NEC_APC3_8x16-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_LE_Model_D_Mono.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SeequaCm.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy1K-II_200L.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Apricot_200L-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SanyoMBC16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaT300_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_MBytePC230_Mono.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Copam_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Phoenix_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EpsonMGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_NEC_APC3_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_8x16-2x.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_DOS_ISO9-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Acer710_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Amstrad_PC.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_8x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Mindset.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_VTech_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_BIOS-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_LE_Model_D_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SeequaCm-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DTK_BIOS.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Conv.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SperryPC_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_CGAthin-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATT_PC6300.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Mindset-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Compis.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_BIOS-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy1K-II_Mono.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Wyse700a-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x16-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Mindset-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy1K-I_200L-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_9x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaTxL1_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt3.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_PhoenixEGA_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaSat_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy1K-I_200L.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt2.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaTxL2_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Trident_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Conv-2x.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaSat_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Acer_VGA_9x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Apricot_Mono.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy2K.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_CGAthin-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_PhoenixEGA_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_Conv-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_PhoenixEGA_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_AMI_EGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt1.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Cordata_PPC-400.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_CompaqThin_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_ToshibaTxL1_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Paradise132_7x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Tandy2K-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Copam_BIOS.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EpsonMGA_Alt-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Phoenix_BIOS.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Apricot_200L.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_PhoenixEGA_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Kaypro2K_G.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Olivetti_M15-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_8x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EagleSpCGA_Alt2-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_AMI_EGA_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DG_One-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EpsonMGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SperryPC_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Nix8810_M35-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DG_One_Alt.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_DOS_ISO8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Acer_VGA_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_8x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_AST_PremiumExec.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Olivetti_M15.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_8x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_MBytePC230_CGA-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ApricotPortable.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaT300_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_Amstrad_PC-2y.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ApricotXenC.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_DTK_BIOS-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_VTech_BIOS.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_VGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_9x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_EGA_8x8-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_MBytePC230_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Wyse700b-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaTxL1_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_BIOS.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_PGC.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_NEC_APC3_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_VGA_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Kaypro2K_G-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_CGAthin.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_9x14.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_AMI_EGA_8x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Nix8810_M16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ATI_SmallW_6x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_EGA_9x14-2x.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_Amstrad_PC.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Verite_8x8-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_SperryPC_8x16.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EverexME_5x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ITT_Xtra.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_Tandy1K-II_200L-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EpsonMGA_Mono.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_EverexME_7x8.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_MBytePC230_EGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ITT_Xtra-2y.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_IBM_PGC-2x.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Cordata_PPC-21.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_Cordata_PPC-400.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Siemens_PC-D.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Acer710_CGA.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Paradise132_7x9.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_Nix8810_M15.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_CGAthin.ttf"
  font "ttf - Ac (aspect-corrected)/Ac437_ToshibaSat_9x16.ttf"
  font "ttf - Ac (aspect-corrected)/AcPlus_IBM_BIOS.ttf"
end
