# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-ranchers' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/ranchers/Ranchers-Regular.ttf'
  name 'Ranchers'
  homepage 'https://fonts.google.com/specimen/Ranchers'

  font 'Ranchers-Regular.ttf'
end
