cask "font-udev-gothic" do
  version "1.2.1"
  sha256 "27ce8efce29c05142e75684ab1eb62902f920358cfb47638c53ebf41b1f19c30"

  url "https://github.com/yuru7/udev-gothic/releases/download/v#{version}/UDEVGothic_v#{version}.zip"
  name "UDEV Gothic"
  desc "Integrate fonts from BIZ UD Gothic and JetBrains Mono"
  homepage "https://github.com/yuru7/udev-gothic/"

  font "UDEVGothic_v#{version}/UDEVGothic-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic-Regular.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35-Regular.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35JPDOC-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35JPDOC-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35JPDOC-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35JPDOC-Regular.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35LG-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35LG-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35LG-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothic35LG-Regular.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicJPDOC-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicJPDOC-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicJPDOC-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicJPDOC-Regular.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicLG-Bold.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicLG-BoldItalic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicLG-Italic.ttf"
  font "UDEVGothic_v#{version}/UDEVGothicLG-Regular.ttf"
end
