# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-yellowtail' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/apache/yellowtail/Yellowtail-Regular.ttf'
  name 'Yellowtail'
  homepage 'https://fonts.google.com/specimen/Yellowtail'

  font 'Yellowtail-Regular.ttf'
end
