cask "font-meslo-lg-nerd-font" do
  version "2.2.0"
  sha256 "8f5d37edd06075adc3d7a7c2303414e69cde06afcbd05e88824257157878ff75"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Meslo.zip"
  name "MesloLG Nerd Font families (Meslo LG)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  font "Meslo LG M Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG M Bold Nerd Font Complete.ttf"
  font "Meslo LG M Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG M Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG M Regular Nerd Font Complete.ttf"
  font "Meslo LG M Italic Nerd Font Complete.ttf"
  font "Meslo LG M Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Nerd Font Complete.ttf"
  font "Meslo LG L Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG L Regular Nerd Font Complete.ttf"
  font "Meslo LG L Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG L Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L Italic Nerd Font Complete.ttf"
  font "Meslo LG S Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG S Bold Nerd Font Complete.ttf"
  font "Meslo LG S Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG S Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S Regular Nerd Font Complete.ttf"
  font "Meslo LG S Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG S Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S Italic Nerd Font Complete.ttf"
  font "Meslo LG L DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG L DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG L DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG L DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG L DZ Italic Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG M DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG M DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG M DZ Italic Nerd Font Complete.ttf"
  font "Meslo LG S DZ Bold Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Bold Nerd Font Complete.ttf"
  font "Meslo LG S DZ Bold Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Bold Italic Nerd Font Complete.ttf"
  font "Meslo LG S DZ Regular Nerd Font Complete.ttf"
  font "Meslo LG S DZ Regular Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Italic Nerd Font Complete Mono.ttf"
  font "Meslo LG S DZ Italic Nerd Font Complete.ttf"
end
