# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-enriqueta' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Enriqueta'
  homepage 'https://fonts.google.com/specimen/Enriqueta'

  font 'ofl/enriqueta/Enriqueta-Bold.ttf'
  font 'ofl/enriqueta/Enriqueta-Medium.ttf'
  font 'ofl/enriqueta/Enriqueta-Regular.ttf'
  font 'ofl/enriqueta/Enriqueta-SemiBold.ttf'
end
