# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-maitree' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Maitree'
  homepage 'https://fonts.google.com/specimen/Maitree'

  font 'ofl/maitree/Maitree-Bold.ttf'
  font 'ofl/maitree/Maitree-ExtraLight.ttf'
  font 'ofl/maitree/Maitree-Light.ttf'
  font 'ofl/maitree/Maitree-Medium.ttf'
  font 'ofl/maitree/Maitree-Regular.ttf'
  font 'ofl/maitree/Maitree-SemiBold.ttf'
end
