# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-yatra-one' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/yatraone/YatraOne-Regular.ttf'
  name 'Yatra One'
  homepage 'https://fonts.google.com/specimen/Yatra+One'

  font 'YatraOne-Regular.ttf'
end
