# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-be-vietnam' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Be Vietnam'
  homepage 'https://fonts.google.com/specimen/Be+Vietnam'

  font 'ofl/bevietnam/BeVietnam-Bold.ttf'
  font 'ofl/bevietnam/BeVietnam-BoldItalic.ttf'
  font 'ofl/bevietnam/BeVietnam-ExtraBold.ttf'
  font 'ofl/bevietnam/BeVietnam-ExtraBoldItalic.ttf'
  font 'ofl/bevietnam/BeVietnam-Italic.ttf'
  font 'ofl/bevietnam/BeVietnam-Light.ttf'
  font 'ofl/bevietnam/BeVietnam-LightItalic.ttf'
  font 'ofl/bevietnam/BeVietnam-Medium.ttf'
  font 'ofl/bevietnam/BeVietnam-MediumItalic.ttf'
  font 'ofl/bevietnam/BeVietnam-Regular.ttf'
  font 'ofl/bevietnam/BeVietnam-SemiBold.ttf'
  font 'ofl/bevietnam/BeVietnam-SemiBoldItalic.ttf'
  font 'ofl/bevietnam/BeVietnam-Thin.ttf'
  font 'ofl/bevietnam/BeVietnam-ThinItalic.ttf'
end
