# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-butcherman' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/butcherman/Butcherman-Regular.ttf'
  name 'Butcherman'
  homepage 'https://fonts.google.com/specimen/Butcherman'

  font 'Butcherman-Regular.ttf'
end
