# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-karla-tamil-upright' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Karla Tamil Upright'
  homepage 'https://fonts.google.com/specimen/Karla+Tamil+Upright'

  font 'ofl/karlatamilupright/KarlaTamilUpright-Bold.ttf'
  font 'ofl/karlatamilupright/KarlaTamilUpright-Regular.ttf'
end
