# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-old-standard-tt' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Old Standard TT'
  homepage 'https://fonts.google.com/specimen/Old+Standard+TT'

  font 'ofl/oldstandardtt/OldStandard-Bold.ttf'
  font 'ofl/oldstandardtt/OldStandard-Italic.ttf'
  font 'ofl/oldstandardtt/OldStandard-Regular.ttf'
end
