cask "font-libertinus" do
  version "7.031"
  sha256 "32cdd2cbd9927b9bda1d500c50faefffa0e1d989b4fbb3ea010dc3efd4495eb0"

  url "https://github.com/alerque/libertinus/releases/download/v#{version}/Libertinus-#{version}.tar.xz"
  appcast "https://github.com/alerque/libertinus/releases.atom"
  name "Libertinus"
  desc "Proportional serif typeface inspired by 19th century book type"
  homepage "https://github.com/alerque/libertinus"

  font "Libertinus-#{version}/static/OTF/LibertinusKeyboard-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusMath-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusMono-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Bold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Italic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSans-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Bold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-BoldItalic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Italic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-Semibold.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerif-SemiboldItalic.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerifDisplay-Regular.otf"
  font "Libertinus-#{version}/static/OTF/LibertinusSerifInitials-Regular.otf"
end
