cask "font-hubot-sans" do
  version "1.0.1"
  sha256 "b460d36097a5c9a3e45710cbe1554589eaa5765d7c2c88df364516f3e27159b1"

  url "https://github.com/github/hubot-sans/releases/download/v#{version}/Hubot-Sans.zip"
  name "Hubot-Sans"
  desc "Hubot Sans, a variable font from GitHub"
  homepage "https://github.com/github/hubot-sans"

  font "Hubot Sans/OTF/Hubot-Sans-Black.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BlackWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-Bold.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-BoldWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBold.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraBoldWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLight.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-ExtraLightWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-Light.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-LightWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-Medium.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-MediumWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-Regular.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-RegularWideItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBold.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldNarrow.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldNarrowItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldSemi.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldSemiItalic.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldWide.otf"
  font "Hubot Sans/OTF/Hubot-Sans-SemiBoldWideItalic.otf"

  # No zap stanza required
end
