# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-sorts-mill-goudy' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Sorts Mill Goudy'
  homepage 'https://fonts.google.com/specimen/Sorts+Mill+Goudy'

  font 'ofl/sortsmillgoudy/SortsMillGoudy-Italic.ttf'
  font 'ofl/sortsmillgoudy/SortsMillGoudy-Regular.ttf'
end
