class FontRoboto < Cask
  version '1.200311'
  sha256 '5101b5bdb3b7b14cc922a771ba068bfcae8634467c1f446bc89bc2b4f8b4f1b5'

  url 'http://developer.android.com/downloads/design/roboto-1.2.zip'
  homepage 'http://developer.android.com/design/style/typography.html'

  font 'Roboto_v1.2/Roboto/Roboto-Black.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-BlackItalic.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Bold.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-BoldItalic.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Italic.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Light.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-LightItalic.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Medium.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-MediumItalic.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Regular.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-Thin.ttf'
  font 'Roboto_v1.2/Roboto/Roboto-ThinItalic.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-Bold.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-BoldItalic.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-Italic.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-Light.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-LightItalic.ttf'
  font 'Roboto_v1.2/RobotoCondensed/RobotoCondensed-Regular.ttf'
end
