cask "font-hk-grotesk" do
  version :latest
  sha256 :no_check

  # This font can be freely downloaded from the homepage linked below,
  # but the download link is uniquely generated by the ecommerce site
  url "https://www.fontsquirrel.com/fonts/download/hk-grotesk",
      verified: "fontsquirrel.com/fonts/download/hk-grotesk"
  name "HK Grotesk"
  homepage "https://hanken.co/collections/free/products/hk-grotesk"

  font "HKGrotesk-Black.otf"
  font "HKGrotesk-Bold.otf"
  font "HKGrotesk-BoldItalic.otf"
  font "HKGrotesk-BoldLegacy.otf"
  font "HKGrotesk-BoldLegacyItalic.otf"
  font "HKGrotesk-ExtraBold.otf"
  font "HKGrotesk-Italic.otf"
  font "HKGrotesk-LegacyItalic.otf"
  font "HKGrotesk-Light.otf"
  font "HKGrotesk-LightItalic.otf"
  font "HKGrotesk-LightLegacy.otf"
  font "HKGrotesk-LightLegacyItalic.otf"
  font "HKGrotesk-Medium.otf"
  font "HKGrotesk-MediumItalic.otf"
  font "HKGrotesk-MediumLegacy.otf"
  font "HKGrotesk-MediumLegacyItalic.otf"
  font "HKGrotesk-Regular.otf"
  font "HKGrotesk-RegularLegacy.otf"
  font "HKGrotesk-SemiBold.otf"
  font "HKGrotesk-SemiBoldItalic.otf"
  font "HKGrotesk-SemiBoldLegacy.otf"
  font "HKGrotesk-SemiBoldLegacyItalic.otf"
end
