# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-yantramanav' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Yantramanav'
  homepage 'https://fonts.google.com/specimen/Yantramanav'

  font 'ofl/yantramanav/Yantramanav-Black.ttf'
  font 'ofl/yantramanav/Yantramanav-Bold.ttf'
  font 'ofl/yantramanav/Yantramanav-Light.ttf'
  font 'ofl/yantramanav/Yantramanav-Medium.ttf'
  font 'ofl/yantramanav/Yantramanav-Regular.ttf'
  font 'ofl/yantramanav/Yantramanav-Thin.ttf'
end
