cask 'font-meslo-nerd-font-mono' do
  version '2.1.0'
  sha256 'f0630f93b2f8c27b0cda8c4a2bae2b7a67bdd70786500e109f38c3a9b145f523'

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Meslo.zip"
  appcast 'https://github.com/ryanoasis/nerd-fonts/releases.atom'
  name 'Meslo Nerd Font (Meslo)'
  homepage 'https://github.com/ryanoasis/nerd-fonts'

  font 'Meslo LG L Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG M Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG S Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG L DZ Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG M DZ Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG S DZ Regular Nerd Font Complete Mono.ttf'
  font 'Meslo LG L Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG M Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG S Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG L DZ Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG M DZ Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG S DZ Bold Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG L Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG M Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG S Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG L DZ Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG M DZ Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG S DZ Bold Nerd Font Complete Mono.ttf'
  font 'Meslo LG L Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG M Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG S Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG L DZ Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG M DZ Italic Nerd Font Complete Mono.ttf'
  font 'Meslo LG S DZ Italic Nerd Font Complete Mono.ttf'
end
