# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-dm-serif-display' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'DM Serif Display'
  homepage 'https://fonts.google.com/specimen/DM+Serif+Display'

  font 'ofl/dmserifdisplay/DMSerifDisplay-Italic.ttf'
  font 'ofl/dmserifdisplay/DMSerifDisplay-Regular.ttf'
end
