# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-inknut-antiqua' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Inknut Antiqua'
  homepage 'https://fonts.google.com/specimen/Inknut+Antiqua'

  font 'ofl/inknutantiqua/InknutAntiqua-Black.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-Bold.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-ExtraBold.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-Light.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-Medium.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-Regular.ttf'
  font 'ofl/inknutantiqua/InknutAntiqua-SemiBold.ttf'
end
