# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-dm-mono' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'DM Mono'
  homepage 'https://fonts.google.com/specimen/DM+Mono'

  font 'ofl/dmmono/DMMono-Italic.ttf'
  font 'ofl/dmmono/DMMono-Light.ttf'
  font 'ofl/dmmono/DMMono-LightItalic.ttf'
  font 'ofl/dmmono/DMMono-Medium.ttf'
  font 'ofl/dmmono/DMMono-MediumItalic.ttf'
  font 'ofl/dmmono/DMMono-Regular.ttf'
end
