# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-im-fell-english' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'IM Fell English'
  homepage 'https://fonts.google.com/specimen/IM+Fell+English'

  font 'ofl/imfellenglish/IMFeENit28P.ttf'
  font 'ofl/imfellenglish/IMFeENrm28P.ttf'
end
