cask "font-iosevka-nerd-font" do
  version "3.0.0"
  sha256 "104fe5998982ed8f55cc05069f325bf886da8dfa6036dc4113f198594f9b481b"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Iosevka.zip"
  name "Iosevka Nerd Font families (Iosevka)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "Iosevka Nerd Font Complete Bold Italic.ttf"
  font "Iosevka Nerd Font Complete Bold Oblique.ttf"
  font "Iosevka Nerd Font Complete Bold.ttf"
  font "Iosevka Nerd Font Complete ExtraBold Italic.ttf"
  font "Iosevka Nerd Font Complete ExtraBold Oblique.ttf"
  font "Iosevka Nerd Font Complete ExtraBold.ttf"
  font "Iosevka Nerd Font Complete ExtraLight Italic.ttf"
  font "Iosevka Nerd Font Complete ExtraLight Oblique.ttf"
  font "Iosevka Nerd Font Complete ExtraLight.ttf"
  font "Iosevka Nerd Font Complete Heavy Italic.ttf"
  font "Iosevka Nerd Font Complete Heavy Oblique.ttf"
  font "Iosevka Nerd Font Complete Heavy.ttf"
  font "Iosevka Nerd Font Complete Italic.ttf"
  font "Iosevka Nerd Font Complete Light Italic.ttf"
  font "Iosevka Nerd Font Complete Light Oblique.ttf"
  font "Iosevka Nerd Font Complete Light.ttf"
  font "Iosevka Nerd Font Complete Medium Italic.ttf"
  font "Iosevka Nerd Font Complete Medium Oblique.ttf"
  font "Iosevka Nerd Font Complete Medium.ttf"
  font "Iosevka Nerd Font Complete Mono Bold Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Bold Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono Bold.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraBold Italic.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraBold Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraBold.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraLight Italic.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraLight Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono ExtraLight.ttf"
  font "Iosevka Nerd Font Complete Mono Heavy Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Heavy Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono Heavy.ttf"
  font "Iosevka Nerd Font Complete Mono Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Light Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Light Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono Light.ttf"
  font "Iosevka Nerd Font Complete Mono Medium Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Medium Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono Medium.ttf"
  font "Iosevka Nerd Font Complete Mono Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono SemiBold Italic.ttf"
  font "Iosevka Nerd Font Complete Mono SemiBold Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono SemiBold.ttf"
  font "Iosevka Nerd Font Complete Mono Thin Italic.ttf"
  font "Iosevka Nerd Font Complete Mono Thin Oblique.ttf"
  font "Iosevka Nerd Font Complete Mono Thin.ttf"
  font "Iosevka Nerd Font Complete Mono.ttf"
  font "Iosevka Nerd Font Complete Oblique.ttf"
  font "Iosevka Nerd Font Complete SemiBold Italic.ttf"
  font "Iosevka Nerd Font Complete SemiBold Oblique.ttf"
  font "Iosevka Nerd Font Complete SemiBold.ttf"
  font "Iosevka Nerd Font Complete Thin Italic.ttf"
  font "Iosevka Nerd Font Complete Thin Oblique.ttf"
  font "Iosevka Nerd Font Complete Thin.ttf"
  font "Iosevka Nerd Font Complete.ttf"
  font "Iosevka Term Nerd Font Complete Bold Italic.ttf"
  font "Iosevka Term Nerd Font Complete Bold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Bold.ttf"
  font "Iosevka Term Nerd Font Complete ExtraBold Italic.ttf"
  font "Iosevka Term Nerd Font Complete ExtraBold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete ExtraBold.ttf"
  font "Iosevka Term Nerd Font Complete ExtraLight Italic.ttf"
  font "Iosevka Term Nerd Font Complete ExtraLight Oblique.ttf"
  font "Iosevka Term Nerd Font Complete ExtraLight.ttf"
  font "Iosevka Term Nerd Font Complete Heavy Italic.ttf"
  font "Iosevka Term Nerd Font Complete Heavy Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Heavy.ttf"
  font "Iosevka Term Nerd Font Complete Italic.ttf"
  font "Iosevka Term Nerd Font Complete Light Italic.ttf"
  font "Iosevka Term Nerd Font Complete Light Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Light.ttf"
  font "Iosevka Term Nerd Font Complete Medium Italic.ttf"
  font "Iosevka Term Nerd Font Complete Medium Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Medium.ttf"
  font "Iosevka Term Nerd Font Complete Mono Bold Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Bold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono Bold.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraBold Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraBold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraBold.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraLight Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraLight Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono ExtraLight.ttf"
  font "Iosevka Term Nerd Font Complete Mono Heavy Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Heavy Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono Heavy.ttf"
  font "Iosevka Term Nerd Font Complete Mono Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Light Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Light Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono Light.ttf"
  font "Iosevka Term Nerd Font Complete Mono Medium Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Medium Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono Medium.ttf"
  font "Iosevka Term Nerd Font Complete Mono Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono SemiBold Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono SemiBold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono SemiBold.ttf"
  font "Iosevka Term Nerd Font Complete Mono Thin Italic.ttf"
  font "Iosevka Term Nerd Font Complete Mono Thin Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Mono Thin.ttf"
  font "Iosevka Term Nerd Font Complete Mono.ttf"
  font "Iosevka Term Nerd Font Complete Oblique.ttf"
  font "Iosevka Term Nerd Font Complete SemiBold Italic.ttf"
  font "Iosevka Term Nerd Font Complete SemiBold Oblique.ttf"
  font "Iosevka Term Nerd Font Complete SemiBold.ttf"
  font "Iosevka Term Nerd Font Complete Thin Italic.ttf"
  font "Iosevka Term Nerd Font Complete Thin Oblique.ttf"
  font "Iosevka Term Nerd Font Complete Thin.ttf"
  font "Iosevka Term Nerd Font Complete.ttf"
end
