# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-averia-serif-libre' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Averia Serif Libre'
  homepage 'https://fonts.google.com/specimen/Averia+Serif+Libre'

  font 'ofl/averiaseriflibre/AveriaSerifLibre-Bold.ttf'
  font 'ofl/averiaseriflibre/AveriaSerifLibre-BoldItalic.ttf'
  font 'ofl/averiaseriflibre/AveriaSerifLibre-Italic.ttf'
  font 'ofl/averiaseriflibre/AveriaSerifLibre-Light.ttf'
  font 'ofl/averiaseriflibre/AveriaSerifLibre-LightItalic.ttf'
  font 'ofl/averiaseriflibre/AveriaSerifLibre-Regular.ttf'
end
