cask "font-coelacanth" do
  version "0.9.0"
  sha256 "11625cc8d840c86054b9f5ab94ce28b74bea1145d241392b027b07e4dff97f63"

  url "https://github.com/Fuzzypeg/Coelacanth/archive/refs/tags/#{version}.zip"
  name "Coelacanth"
  desc "Serif typeface inspired by Bruce Rogers' Centaur"
  homepage "https://github.com/Fuzzypeg/Coelacanth"

  font "Coelacanth.otf"
  font "CoelacanthBold.otf"
  font "CoelacanthCaption.otf"
  font "CoelacanthCaptionBold.otf"
  font "CoelacanthCaptionExtraLt.otf"
  font "CoelacanthCaptionHeavy.otf"
  font "CoelacanthCaptionIt.otf"
  font "CoelacanthCaptionLt.otf"
  font "CoelacanthCaptionSemibd.otf"
  font "CoelacanthDisplay.otf"
  font "CoelacanthDisplayBold.otf"
  font "CoelacanthDisplayExtraLt.otf"
  font "CoelacanthDisplayHeavy.otf"
  font "CoelacanthDisplayLt.otf"
  font "CoelacanthDisplaySemibd.otf"
  font "CoelacanthExtraLt.otf"
  font "CoelacanthHeavy.otf"
  font "CoelacanthIt.otf"
  font "CoelacanthLt.otf"
  font "CoelacanthPearl.otf"
  font "CoelacanthPearlBold.otf"
  font "CoelacanthPearlExtraLt.otf"
  font "CoelacanthPearlHeavy.otf"
  font "CoelacanthPearlIt.otf"
  font "CoelacanthPearlLt.otf"
  font "CoelacanthPearlSemibd.otf"
  font "CoelacanthSemibd.otf"
  font "CoelacanthSubcapt.otf"
  font "CoelacanthSubcaptBold.otf"
  font "CoelacanthSubcaptExtraLt.otf"
  font "CoelacanthSubcaptHeavy.otf"
  font "CoelacanthSubcaptIt.otf"
  font "CoelacanthSubcaptLt.otf"
  font "CoelacanthSubcaptSemibd.otf"
  font "CoelacanthSubhd.otf"
  font "CoelacanthSubhdBold.otf"
  font "CoelacanthSubhdExtraLt.otf"
  font "CoelacanthSubhdHeavy.otf"
  font "CoelacanthSubhdLt.otf"
  font "CoelacanthSubhdSemibd.otf"
end
