# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-fascinate' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/fascinate/Fascinate-Regular.ttf'
  name 'Fascinate'
  homepage 'https://fonts.google.com/specimen/Fascinate'

  font 'Fascinate-Regular.ttf'
end
