cask "font-monaspace-nerd-font" do
  version "3.1.0"
  sha256 "1cc0715b767cc6af619aefac33a0c4e0146efc0300ec75c199b7d615a1da742a"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Monaspace.zip"
  name "Monaspice Nerd Font families (Monaspace)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "MonaspiceArNerdFont-Bold.otf"
  font "MonaspiceArNerdFont-BoldItalic.otf"
  font "MonaspiceArNerdFont-Italic.otf"
  font "MonaspiceArNerdFont-Medium.otf"
  font "MonaspiceArNerdFont-MediumItalic.otf"
  font "MonaspiceArNerdFont-Regular.otf"
  font "MonaspiceArNerdFontMono-Bold.otf"
  font "MonaspiceArNerdFontMono-BoldItalic.otf"
  font "MonaspiceArNerdFontMono-Italic.otf"
  font "MonaspiceArNerdFontMono-Medium.otf"
  font "MonaspiceArNerdFontMono-MediumItalic.otf"
  font "MonaspiceArNerdFontMono-Regular.otf"
  font "MonaspiceArNerdFontPropo-Bold.otf"
  font "MonaspiceArNerdFontPropo-BoldItalic.otf"
  font "MonaspiceArNerdFontPropo-Italic.otf"
  font "MonaspiceArNerdFontPropo-Medium.otf"
  font "MonaspiceArNerdFontPropo-MediumItalic.otf"
  font "MonaspiceArNerdFontPropo-Regular.otf"
  font "MonaspiceKrNerdFont-Bold.otf"
  font "MonaspiceKrNerdFont-BoldItalic.otf"
  font "MonaspiceKrNerdFont-Italic.otf"
  font "MonaspiceKrNerdFont-Medium.otf"
  font "MonaspiceKrNerdFont-MediumItalic.otf"
  font "MonaspiceKrNerdFont-Regular.otf"
  font "MonaspiceKrNerdFontMono-Bold.otf"
  font "MonaspiceKrNerdFontMono-BoldItalic.otf"
  font "MonaspiceKrNerdFontMono-Italic.otf"
  font "MonaspiceKrNerdFontMono-Medium.otf"
  font "MonaspiceKrNerdFontMono-MediumItalic.otf"
  font "MonaspiceKrNerdFontMono-Regular.otf"
  font "MonaspiceKrNerdFontPropo-Bold.otf"
  font "MonaspiceKrNerdFontPropo-BoldItalic.otf"
  font "MonaspiceKrNerdFontPropo-Italic.otf"
  font "MonaspiceKrNerdFontPropo-Medium.otf"
  font "MonaspiceKrNerdFontPropo-MediumItalic.otf"
  font "MonaspiceKrNerdFontPropo-Regular.otf"
  font "MonaspiceNeNerdFont-Bold.otf"
  font "MonaspiceNeNerdFont-BoldItalic.otf"
  font "MonaspiceNeNerdFont-Italic.otf"
  font "MonaspiceNeNerdFont-Medium.otf"
  font "MonaspiceNeNerdFont-MediumItalic.otf"
  font "MonaspiceNeNerdFont-Regular.otf"
  font "MonaspiceNeNerdFontMono-Bold.otf"
  font "MonaspiceNeNerdFontMono-BoldItalic.otf"
  font "MonaspiceNeNerdFontMono-Italic.otf"
  font "MonaspiceNeNerdFontMono-Medium.otf"
  font "MonaspiceNeNerdFontMono-MediumItalic.otf"
  font "MonaspiceNeNerdFontMono-Regular.otf"
  font "MonaspiceNeNerdFontPropo-Bold.otf"
  font "MonaspiceNeNerdFontPropo-BoldItalic.otf"
  font "MonaspiceNeNerdFontPropo-Italic.otf"
  font "MonaspiceNeNerdFontPropo-Medium.otf"
  font "MonaspiceNeNerdFontPropo-MediumItalic.otf"
  font "MonaspiceNeNerdFontPropo-Regular.otf"
  font "MonaspiceRnNerdFont-Bold.otf"
  font "MonaspiceRnNerdFont-BoldItalic.otf"
  font "MonaspiceRnNerdFont-Italic.otf"
  font "MonaspiceRnNerdFont-Medium.otf"
  font "MonaspiceRnNerdFont-MediumItalic.otf"
  font "MonaspiceRnNerdFont-Regular.otf"
  font "MonaspiceRnNerdFontMono-Bold.otf"
  font "MonaspiceRnNerdFontMono-BoldItalic.otf"
  font "MonaspiceRnNerdFontMono-Italic.otf"
  font "MonaspiceRnNerdFontMono-Medium.otf"
  font "MonaspiceRnNerdFontMono-MediumItalic.otf"
  font "MonaspiceRnNerdFontMono-Regular.otf"
  font "MonaspiceRnNerdFontPropo-Bold.otf"
  font "MonaspiceRnNerdFontPropo-BoldItalic.otf"
  font "MonaspiceRnNerdFontPropo-Italic.otf"
  font "MonaspiceRnNerdFontPropo-Medium.otf"
  font "MonaspiceRnNerdFontPropo-MediumItalic.otf"
  font "MonaspiceRnNerdFontPropo-Regular.otf"
  font "MonaspiceXeNerdFont-Bold.otf"
  font "MonaspiceXeNerdFont-BoldItalic.otf"
  font "MonaspiceXeNerdFont-Italic.otf"
  font "MonaspiceXeNerdFont-Medium.otf"
  font "MonaspiceXeNerdFont-MediumItalic.otf"
  font "MonaspiceXeNerdFont-Regular.otf"
  font "MonaspiceXeNerdFontMono-Bold.otf"
  font "MonaspiceXeNerdFontMono-BoldItalic.otf"
  font "MonaspiceXeNerdFontMono-Italic.otf"
  font "MonaspiceXeNerdFontMono-Medium.otf"
  font "MonaspiceXeNerdFontMono-MediumItalic.otf"
  font "MonaspiceXeNerdFontMono-Regular.otf"
  font "MonaspiceXeNerdFontPropo-Bold.otf"
  font "MonaspiceXeNerdFontPropo-BoldItalic.otf"
  font "MonaspiceXeNerdFontPropo-Italic.otf"
  font "MonaspiceXeNerdFontPropo-Medium.otf"
  font "MonaspiceXeNerdFontPropo-MediumItalic.otf"
  font "MonaspiceXeNerdFontPropo-Regular.otf"

  # No zap stanza required
end
