cask "font-urbanist" do
  version "1.302"
  sha256 "7d139d674d20831e6b2257f734b1cb700c57cdd8961e26cfb74d8304bdf63aea"

  url "https://github.com/coreywho/Urbanist/releases/download/v#{version}/Urbanist_Font_Family_#{version}.zip"
  name "Urbanist"
  homepage "https://github.com/coreywho/Urbanist"

  font "fonts/variable/Urbanist[ital,wght].ttf"
  font "fonts/otf/Urbanist-Black.otf"
  font "fonts/otf/Urbanist-BlackItalic.otf"
  font "fonts/otf/Urbanist-Bold.otf"
  font "fonts/otf/Urbanist-BoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraBold.otf"
  font "fonts/otf/Urbanist-ExtraBoldItalic.otf"
  font "fonts/otf/Urbanist-ExtraLight.otf"
  font "fonts/otf/Urbanist-ExtraLightItalic.otf"
  font "fonts/otf/Urbanist-Italic.otf"
  font "fonts/otf/Urbanist-Light.otf"
  font "fonts/otf/Urbanist-LightItalic.otf"
  font "fonts/otf/Urbanist-Medium.otf"
  font "fonts/otf/Urbanist-MediumItalic.otf"
  font "fonts/otf/Urbanist-Regular.otf"
  font "fonts/otf/Urbanist-SemiBold.otf"
  font "fonts/otf/Urbanist-SemiBoldItalic.otf"
  font "fonts/otf/Urbanist-Thin.otf"
  font "fonts/otf/Urbanist-ThinItalic.otf"
end
