# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-bad-script' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/badscript/BadScript-Regular.ttf'
  name 'Bad Script'
  homepage 'https://fonts.google.com/specimen/Bad+Script'

  font 'BadScript-Regular.ttf'
end
