cask "font-noto-nerd-font" do
  version "2.3.3"
  sha256 "4df90acc70dba49849bd5e22489c1f16633c6c4010966b97f6a7fb7ce8909237"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Noto.zip"
  name "Noto Nerd Font families (Noto)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "Noto Mono Nerd Font Complete Mono.ttf"
  font "Noto Mono Nerd Font Complete.ttf"
  font "Noto Sans Condensed Black Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Black Nerd Font Complete.ttf"
  font "Noto Sans Condensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Bold Nerd Font Complete.ttf"
  font "Noto Sans Condensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans Condensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Condensed Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Light Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Light Nerd Font Complete.ttf"
  font "Noto Sans Condensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Medium Nerd Font Complete.ttf"
  font "Noto Sans Condensed Nerd Font Complete.ttf"
  font "Noto Sans Condensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans Condensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Sans Condensed Thin Nerd Font Complete.ttf"
  font "Noto Sans ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Black Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Black Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Bold Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Light Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Light Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Medium Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraCondensed Thin Nerd Font Complete.ttf"
  font "Noto Sans ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Sans ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Italic Nerd Font Complete.ttf"
  font "Noto Sans Light Italic Nerd Font Complete.ttf"
  font "Noto Sans Light Nerd Font Complete.ttf"
  font "Noto Sans Medium Italic Nerd Font Complete.ttf"
  font "Noto Sans Medium Nerd Font Complete.ttf"
  font "Noto Sans Mono Black Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Black Nerd Font Complete.ttf"
  font "Noto Sans Mono Bold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Bold Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Black Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Black Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Bold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Bold Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed ExtraBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed ExtraLight Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Light Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Light Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Medium Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Medium Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed SemiBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans Mono Condensed Thin Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Condensed Thin Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Black Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Black Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Bold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Bold Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed ExtraBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed ExtraLight Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Light Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Light Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Medium Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Medium Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed SemiBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraCondensed Thin Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraCondensed Thin Nerd Font Complete.ttf"
  font "Noto Sans Mono ExtraLight Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Mono Light Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Light Nerd Font Complete.ttf"
  font "Noto Sans Mono Medium Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Medium Nerd Font Complete.ttf"
  font "Noto Sans Mono Regular Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Regular Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiBold Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Black Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Black Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Bold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Bold Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed ExtraBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed ExtraLight Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Light Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Light Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Medium Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Medium Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed SemiBold Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans Mono SemiCondensed Thin Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono SemiCondensed Thin Nerd Font Complete.ttf"
  font "Noto Sans Mono Thin Nerd Font Complete Mono.ttf"
  font "Noto Sans Mono Thin Nerd Font Complete.ttf"
  font "Noto Sans Regular Nerd Font Complete.ttf"
  font "Noto Sans SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiBold Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Black Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Black Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Bold Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Light Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Light Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Medium Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Sans SemiCondensed Thin Nerd Font Complete.ttf"
  font "Noto Sans Thin Italic Nerd Font Complete.ttf"
  font "Noto Sans Thin Nerd Font Complete.ttf"
  font "Noto Serif Black Italic Nerd Font Complete.ttf"
  font "Noto Serif Black Nerd Font Complete.ttf"
  font "Noto Serif Bold Italic Nerd Font Complete.ttf"
  font "Noto Serif Bold Nerd Font Complete.ttf"
  font "Noto Serif Condensed Black Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Black Nerd Font Complete.ttf"
  font "Noto Serif Condensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Bold Nerd Font Complete.ttf"
  font "Noto Serif Condensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Serif Condensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Serif Condensed Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Light Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Light Nerd Font Complete.ttf"
  font "Noto Serif Condensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Medium Nerd Font Complete.ttf"
  font "Noto Serif Condensed Nerd Font Complete.ttf"
  font "Noto Serif Condensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed SemiBold Nerd Font Complete.ttf"
  font "Noto Serif Condensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Serif Condensed Thin Nerd Font Complete.ttf"
  font "Noto Serif ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraBold Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Black Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Black Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Bold Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Light Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Light Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Medium Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraCondensed Thin Nerd Font Complete.ttf"
  font "Noto Serif ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Serif ExtraLight Nerd Font Complete.ttf"
  font "Noto Serif Italic Nerd Font Complete.ttf"
  font "Noto Serif Light Italic Nerd Font Complete.ttf"
  font "Noto Serif Light Nerd Font Complete.ttf"
  font "Noto Serif Medium Italic Nerd Font Complete.ttf"
  font "Noto Serif Medium Nerd Font Complete.ttf"
  font "Noto Serif Regular Nerd Font Complete.ttf"
  font "Noto Serif SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiBold Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Black Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Black Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Bold Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Bold Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed ExtraBold Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed ExtraBold Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed ExtraLight Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed ExtraLight Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Light Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Light Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Medium Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Medium Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed SemiBold Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed SemiBold Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Thin Italic Nerd Font Complete.ttf"
  font "Noto Serif SemiCondensed Thin Nerd Font Complete.ttf"
  font "Noto Serif Thin Italic Nerd Font Complete.ttf"
  font "Noto Serif Thin Nerd Font Complete.ttf"
end
