# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-amaranth' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts.git'
  name 'Amaranth'
  homepage 'https://fonts.google.com/specimen/Amaranth'

  font 'ofl/amaranth/Amaranth-Bold.ttf'
  font 'ofl/amaranth/Amaranth-BoldItalic.ttf'
  font 'ofl/amaranth/Amaranth-Italic.ttf'
  font 'ofl/amaranth/Amaranth-Regular.ttf'
end
