# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-yesteryear' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/yesteryear/Yesteryear-Regular.ttf'
  name 'Yesteryear'
  homepage 'https://fonts.google.com/specimen/Yesteryear'

  font 'Yesteryear-Regular.ttf'
end
