# THIS FILE WAS AUTOMATICALLY GENERATED BY import_google_fonts
cask 'font-kreon' do
  version :latest
  sha256 :no_check

  # github.com/google/fonts/ was verified as official when first introduced to the cask
  url 'https://github.com/google/fonts/raw/master/ofl/kreon/Kreon%5Bwght%5D.ttf'
  name 'Kreon'
  homepage 'https://fonts.google.com/specimen/Kreon'

  font 'Kreon[wght].ttf'
end
