cask "font-liberation-nerd-font" do
  version "2.1.0"
  sha256 "30b0e02385c43c92a9556689eda6c83731525c431f6eba9dad556b3512aa77a5"

  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/LiberationMono.zip"
  appcast "https://github.com/ryanoasis/nerd-fonts/releases.atom"
  name "Literation Nerd Font families (Liberation)"
  homepage "https://github.com/ryanoasis/nerd-fonts"

  font "Literation Mono Nerd Font Complete Mono.ttf"
  font "Literation Serif Bold Italic Nerd Font Complete.ttf"
  font "Literation Sans Bold Italic Nerd Font Complete Mono.ttf"
  font "Literation Mono Italic Nerd Font Complete Mono.ttf"
  font "Literation Sans Nerd Font Complete Mono.ttf"
  font "Literation Mono Bold Nerd Font Complete.ttf"
  font "Literation Serif Nerd Font Complete.ttf"
  font "Literation Serif Nerd Font Complete Mono.ttf"
  font "Literation Sans Bold Nerd Font Complete.ttf"
  font "Literation Mono Italic Nerd Font Complete.ttf"
  font "Literation Serif Bold Italic Nerd Font Complete Mono.ttf"
  font "Literation Mono Bold Nerd Font Complete Mono.ttf"
  font "Literation Serif Italic Nerd Font Complete.ttf"
  font "Literation Serif Bold Nerd Font Complete Mono.ttf"
  font "Literation Sans Bold Nerd Font Complete Mono.ttf"
  font "Literation Serif Italic Nerd Font Complete Mono.ttf"
  font "Literation Mono Bold Italic Nerd Font Complete.ttf"
  font "Literation Sans Italic Nerd Font Complete.ttf"
  font "Literation Sans Bold Italic Nerd Font Complete.ttf"
  font "Literation Sans Nerd Font Complete.ttf"
  font "Literation Sans Italic Nerd Font Complete Mono.ttf"
  font "Literation Mono Nerd Font Complete.ttf"
  font "Literation Serif Bold Nerd Font Complete.ttf"
  font "Literation Mono Bold Italic Nerd Font Complete Mono.ttf"
end
