class FontDejavu < Cask
  url 'http://downloads.sourceforge.net/sourceforge/dejavu/dejavu-fonts-ttf-2.34.zip'
  homepage 'http://dejavu-fonts.org/wiki/Main_Page'
  version '2.34'
  sha1 '3417fdcb2bc9a2fb02aff9b8ee8eb236e678ead1'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-ExtraLight.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSans.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansCondensed.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-BoldOblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono-Oblique.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSansMono.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-BoldItalic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif-Italic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerif.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-Bold.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-BoldItalic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed-Italic.ttf'
  font 'dejavu-fonts-ttf-2.34/ttf/DejaVuSerifCondensed.ttf'
end
