class FontNotoSansLao < Formula
  desc "Noto Sans Lao"
  homepage "https://www.google.com/get/noto/#sans-laoo"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansLao-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansLao-Black.ttf"
    (share/"fonts").install "NotoSansLao-Bold.ttf"
    (share/"fonts").install "NotoSansLao-Condensed.ttf"
    (share/"fonts").install "NotoSansLao-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansLao-CondensedBold.ttf"
    (share/"fonts").install "NotoSansLao-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLao-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLao-CondensedLight.ttf"
    (share/"fonts").install "NotoSansLao-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansLao-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLao-CondensedThin.ttf"
    (share/"fonts").install "NotoSansLao-ExtraBold.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLao-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansLao-ExtraLight.ttf"
    (share/"fonts").install "NotoSansLao-Light.ttf"
    (share/"fonts").install "NotoSansLao-Medium.ttf"
    (share/"fonts").install "NotoSansLao-Regular.ttf"
    (share/"fonts").install "NotoSansLao-SemiBold.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLao-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansLao-Thin.ttf"
    (share/"fonts").install "NotoSansLaoUI-Black.ttf"
    (share/"fonts").install "NotoSansLaoUI-Bold.ttf"
    (share/"fonts").install "NotoSansLaoUI-Condensed.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansLaoUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-Light.ttf"
    (share/"fonts").install "NotoSansLaoUI-Medium.ttf"
    (share/"fonts").install "NotoSansLaoUI-Regular.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansLaoUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansLaoUI-Thin.ttf"
  end

  test do
  end
end
