class FontNotoSansThai < Formula
  desc "Noto Sans Thai"
  homepage "https://www.google.com/get/noto/#sans-thai"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansThai-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansThai-Black.ttf"
    (share/"fonts").install "NotoSansThai-Bold.ttf"
    (share/"fonts").install "NotoSansThai-Condensed.ttf"
    (share/"fonts").install "NotoSansThai-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansThai-CondensedBold.ttf"
    (share/"fonts").install "NotoSansThai-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThai-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThai-CondensedLight.ttf"
    (share/"fonts").install "NotoSansThai-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansThai-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThai-CondensedThin.ttf"
    (share/"fonts").install "NotoSansThai-ExtraBold.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThai-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansThai-ExtraLight.ttf"
    (share/"fonts").install "NotoSansThai-Light.ttf"
    (share/"fonts").install "NotoSansThai-Medium.ttf"
    (share/"fonts").install "NotoSansThai-Regular.ttf"
    (share/"fonts").install "NotoSansThai-SemiBold.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThai-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansThai-Thin.ttf"
    (share/"fonts").install "NotoSansThaiUI-Black.ttf"
    (share/"fonts").install "NotoSansThaiUI-Bold.ttf"
    (share/"fonts").install "NotoSansThaiUI-Condensed.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansThaiUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-Light.ttf"
    (share/"fonts").install "NotoSansThaiUI-Medium.ttf"
    (share/"fonts").install "NotoSansThaiUI-Regular.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansThaiUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansThaiUI-Thin.ttf"
  end

  test do
  end
end
