class FontNotoSerif < Formula
  desc "Noto Serif"
  homepage "https://www.google.com/get/noto/#serif-lgc"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSerif-Black.ttf"
    (share/"fonts").install "NotoSerif-BlackItalic.ttf"
    (share/"fonts").install "NotoSerif-Bold.ttf"
    (share/"fonts").install "NotoSerif-BoldItalic.ttf"
    (share/"fonts").install "NotoSerif-Condensed.ttf"
    (share/"fonts").install "NotoSerif-CondensedBlack.ttf"
    (share/"fonts").install "NotoSerif-CondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedBold.ttf"
    (share/"fonts").install "NotoSerif-CondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerif-CondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerif-CondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedLight.ttf"
    (share/"fonts").install "NotoSerif-CondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedMedium.ttf"
    (share/"fonts").install "NotoSerif-CondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerif-CondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-CondensedThin.ttf"
    (share/"fonts").install "NotoSerif-CondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraBold.ttf"
    (share/"fonts").install "NotoSerif-ExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSerif-ExtraCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerif-ExtraLight.ttf"
    (share/"fonts").install "NotoSerif-ExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerif-Italic.ttf"
    (share/"fonts").install "NotoSerif-Light.ttf"
    (share/"fonts").install "NotoSerif-LightItalic.ttf"
    (share/"fonts").install "NotoSerif-Medium.ttf"
    (share/"fonts").install "NotoSerif-MediumItalic.ttf"
    (share/"fonts").install "NotoSerif-Regular.ttf"
    (share/"fonts").install "NotoSerif-SemiBold.ttf"
    (share/"fonts").install "NotoSerif-SemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensed.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSerif-SemiCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerif-Thin.ttf"
    (share/"fonts").install "NotoSerif-ThinItalic.ttf"
  end

  test do
  end
end
