class FontMPlus < Formula
  desc "M+ FONTS"
  homepage "https://mplus-fonts.osdn.jp/about-en.html"
  url "http://dl.osdn.jp/mplus-fonts/62344/mplus-TESTFLIGHT-#{version}.tar.xz"
  version "063"
  sha256 "149a5c97c35624d79ffb3cbbdd56559319085229acaf72b49b56adc5ede0979c"

  bottle :unneeded

  def install
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-black.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-heavy.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1c-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1m-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1m-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1m-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1m-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1m-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1mn-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1mn-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1mn-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1mn-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1mn-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-black.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-heavy.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-1p-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-black.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-heavy.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2c-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2m-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2m-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2m-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2m-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2m-thin.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-black.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-bold.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-heavy.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-light.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-medium.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-regular.ttf"
    (share/"fonts").install "mplus-TESTFLIGHT-#{version}/mplus-2p-thin.ttf"
  end

  test do
  end
end
