class FontNotoSans < Formula
  desc "Noto Sans"
  homepage "https://www.google.com/get/noto/#sans-lgc"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSans-Black.ttf"
    (share/"fonts").install "NotoSans-BlackItalic.ttf"
    (share/"fonts").install "NotoSans-Bold.ttf"
    (share/"fonts").install "NotoSans-BoldItalic.ttf"
    (share/"fonts").install "NotoSans-Condensed.ttf"
    (share/"fonts").install "NotoSans-CondensedBlack.ttf"
    (share/"fonts").install "NotoSans-CondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedBold.ttf"
    (share/"fonts").install "NotoSans-CondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSans-CondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSans-CondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedLight.ttf"
    (share/"fonts").install "NotoSans-CondensedLightItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedMedium.ttf"
    (share/"fonts").install "NotoSans-CondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSans-CondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSans-CondensedThin.ttf"
    (share/"fonts").install "NotoSans-CondensedThinItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraBold.ttf"
    (share/"fonts").install "NotoSans-ExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSans-ExtraCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSans-ExtraLight.ttf"
    (share/"fonts").install "NotoSans-ExtraLightItalic.ttf"
    (share/"fonts").install "NotoSans-Italic.ttf"
    (share/"fonts").install "NotoSans-Light.ttf"
    (share/"fonts").install "NotoSans-LightItalic.ttf"
    (share/"fonts").install "NotoSans-Medium.ttf"
    (share/"fonts").install "NotoSans-MediumItalic.ttf"
    (share/"fonts").install "NotoSans-Regular.ttf"
    (share/"fonts").install "NotoSans-SemiBold.ttf"
    (share/"fonts").install "NotoSans-SemiBoldItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensed.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSans-SemiCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSans-Thin.ttf"
    (share/"fonts").install "NotoSans-ThinItalic.ttf"
  end

  test do
  end
end
