class FontNotoSansKhmer < Formula
  desc "Noto Sans Khmer"
  homepage "https://www.google.com/get/noto/#sans-khmr"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKhmer-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansKhmer-Black.ttf"
    (share/"fonts").install "NotoSansKhmer-Bold.ttf"
    (share/"fonts").install "NotoSansKhmer-Condensed.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmer-CondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmer-ExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmer-Light.ttf"
    (share/"fonts").install "NotoSansKhmer-Medium.ttf"
    (share/"fonts").install "NotoSansKhmer-Regular.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiBold.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmer-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmer-Thin.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Black.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Bold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Condensed.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmerUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Light.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Medium.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Regular.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansKhmerUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansKhmerUI-Thin.ttf"
  end

  test do
  end
end
