class FontNotoSerifDisplay < Formula
  desc "Noto Serif Display"
  homepage "https://www.google.com/get/noto/#serif-lgc-display"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifDisplay-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSerifDisplay-Black.ttf"
    (share/"fonts").install "NotoSerifDisplay-BlackItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Bold.ttf"
    (share/"fonts").install "NotoSerifDisplay-BoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Condensed.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedBlack.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedMedium.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedThin.ttf"
    (share/"fonts").install "NotoSerifDisplay-CondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-ExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Italic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Light.ttf"
    (share/"fonts").install "NotoSerifDisplay-LightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Medium.ttf"
    (share/"fonts").install "NotoSerifDisplay-MediumItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Regular.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensed.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedBlackItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedExtraLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedLightItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedMediumItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSerifDisplay-SemiCondensedThinItalic.ttf"
    (share/"fonts").install "NotoSerifDisplay-Thin.ttf"
    (share/"fonts").install "NotoSerifDisplay-ThinItalic.ttf"
  end

  test do
  end
end
