class FontFiraSans < Formula
  desc "Fira Sans"
  homepage "https://mozilla.github.io/Fira/"
  url "https://github.com/mozilla/Fira/archive/#{version}.tar.gz"
  version "4.202"
  sha256 "d86269657387f144d77ba12011124f30f423f70672e1576dc16f918bb16ddfe4"

  bottle :unneeded

  def install
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-BoldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Bold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-BookItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Book.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-BoldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Bold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-BookItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Book.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-EightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Eight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-ExtraboldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-ExtraBold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-ExtraLightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-ExtraLight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-FourItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Four.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-HairItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Hair.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-HeavyItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Heavy.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Italic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-LightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Light.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-MediumItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Medium.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Regular.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-SemiboldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-SemiBold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-ThinItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Thin.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-TwoItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Two.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-UltraItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-UltraLightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-UltraLight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSansCondensed-Ultra.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-EightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Eight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-ExtraBoldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-ExtraBold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-ExtraLightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-ExtraLight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-FourItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Four.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-HairItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Hair.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-HeavyItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Heavy.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Italic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-LightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Light.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-MediumItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Medium.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Regular.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-SemiBoldItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-SemiBold.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-ThinItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Thin.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-TwoItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Two.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-UltraItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-UltraLightItalic.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-UltraLight.otf"
    (share/"fonts").install "Fira-#{version}/otf/FiraSans-Ultra.otf"
  end

  test do
  end
end
