class FontNotoSansSinhala < Formula
  desc "Noto Sans Sinhala"
  homepage "https://www.google.com/get/noto/#sans-sinh"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSinhala-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansSinhala-Black.ttf"
    (share/"fonts").install "NotoSansSinhala-Bold.ttf"
    (share/"fonts").install "NotoSansSinhala-Condensed.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhala-CondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhala-ExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhala-Light.ttf"
    (share/"fonts").install "NotoSansSinhala-Medium.ttf"
    (share/"fonts").install "NotoSansSinhala-Regular.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiBold.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhala-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhala-Thin.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Black.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Bold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Condensed.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Light.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Medium.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Regular.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansSinhalaUI-Thin.ttf"
  end

  test do
  end
end
