class FontNotoSansDevanagari < Formula
  desc "Noto Sans Devanagari"
  homepage "https://www.google.com/get/noto/#sans-deva"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDevanagari-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansDevanagari-Black.ttf"
    (share/"fonts").install "NotoSansDevanagari-Bold.ttf"
    (share/"fonts").install "NotoSansDevanagari-Condensed.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-CondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagari-ExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-Light.ttf"
    (share/"fonts").install "NotoSansDevanagari-Medium.ttf"
    (share/"fonts").install "NotoSansDevanagari-Regular.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagari-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagari-Thin.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Black.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Bold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Condensed.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Light.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Medium.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Regular.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansDevanagariUI-Thin.ttf"
  end

  test do
  end
end
