class FontNotoSansTamil < Formula
  desc "Noto Sans Tamil"
  homepage "https://www.google.com/get/noto/#sans-taml"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTamil-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansTamil-Black.ttf"
    (share/"fonts").install "NotoSansTamil-Bold.ttf"
    (share/"fonts").install "NotoSansTamil-Condensed.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedBold.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedLight.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamil-CondensedThin.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraBold.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansTamil-ExtraLight.ttf"
    (share/"fonts").install "NotoSansTamil-Light.ttf"
    (share/"fonts").install "NotoSansTamil-Medium.ttf"
    (share/"fonts").install "NotoSansTamil-Regular.ttf"
    (share/"fonts").install "NotoSansTamil-SemiBold.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamil-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansTamil-Thin.ttf"
    (share/"fonts").install "NotoSansTamilUI-Black.ttf"
    (share/"fonts").install "NotoSansTamilUI-Bold.ttf"
    (share/"fonts").install "NotoSansTamilUI-Condensed.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansTamilUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-Light.ttf"
    (share/"fonts").install "NotoSansTamilUI-Medium.ttf"
    (share/"fonts").install "NotoSansTamilUI-Regular.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansTamilUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansTamilUI-Thin.ttf"
  end

  test do
  end
end
