class FontLatinModern < Formula
  desc "Latin Modern"
  homepage "http://www.gust.org.pl/projects/e-foundry/latin-modern"
  url "http://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm#{version}otf.zip"
  version "2.004"
  sha256 "5b0236051d3728be6616f1b274e3b910473875b5a3ef9382f0ef00384ddb161b"

  bottle :unneeded

  def install
    (share/"fonts").install "lmmono10-italic.otf"
    (share/"fonts").install "lmmono10-regular.otf"
    (share/"fonts").install "lmmono12-regular.otf"
    (share/"fonts").install "lmmono8-regular.otf"
    (share/"fonts").install "lmmono9-regular.otf"
    (share/"fonts").install "lmmonocaps10-oblique.otf"
    (share/"fonts").install "lmmonocaps10-regular.otf"
    (share/"fonts").install "lmmonolt10-bold.otf"
    (share/"fonts").install "lmmonolt10-boldoblique.otf"
    (share/"fonts").install "lmmonolt10-oblique.otf"
    (share/"fonts").install "lmmonolt10-regular.otf"
    (share/"fonts").install "lmmonoltcond10-oblique.otf"
    (share/"fonts").install "lmmonoltcond10-regular.otf"
    (share/"fonts").install "lmmonoprop10-oblique.otf"
    (share/"fonts").install "lmmonoprop10-regular.otf"
    (share/"fonts").install "lmmonoproplt10-bold.otf"
    (share/"fonts").install "lmmonoproplt10-boldoblique.otf"
    (share/"fonts").install "lmmonoproplt10-oblique.otf"
    (share/"fonts").install "lmmonoproplt10-regular.otf"
    (share/"fonts").install "lmmonoslant10-regular.otf"
    (share/"fonts").install "lmroman10-bold.otf"
    (share/"fonts").install "lmroman10-bolditalic.otf"
    (share/"fonts").install "lmroman10-italic.otf"
    (share/"fonts").install "lmroman10-regular.otf"
    (share/"fonts").install "lmroman12-bold.otf"
    (share/"fonts").install "lmroman12-italic.otf"
    (share/"fonts").install "lmroman12-regular.otf"
    (share/"fonts").install "lmroman17-regular.otf"
    (share/"fonts").install "lmroman5-bold.otf"
    (share/"fonts").install "lmroman5-regular.otf"
    (share/"fonts").install "lmroman6-bold.otf"
    (share/"fonts").install "lmroman6-regular.otf"
    (share/"fonts").install "lmroman7-bold.otf"
    (share/"fonts").install "lmroman7-italic.otf"
    (share/"fonts").install "lmroman7-regular.otf"
    (share/"fonts").install "lmroman8-bold.otf"
    (share/"fonts").install "lmroman8-italic.otf"
    (share/"fonts").install "lmroman8-regular.otf"
    (share/"fonts").install "lmroman9-bold.otf"
    (share/"fonts").install "lmroman9-italic.otf"
    (share/"fonts").install "lmroman9-regular.otf"
    (share/"fonts").install "lmromancaps10-oblique.otf"
    (share/"fonts").install "lmromancaps10-regular.otf"
    (share/"fonts").install "lmromandemi10-oblique.otf"
    (share/"fonts").install "lmromandemi10-regular.otf"
    (share/"fonts").install "lmromandunh10-oblique.otf"
    (share/"fonts").install "lmromandunh10-regular.otf"
    (share/"fonts").install "lmromanslant10-bold.otf"
    (share/"fonts").install "lmromanslant10-regular.otf"
    (share/"fonts").install "lmromanslant12-regular.otf"
    (share/"fonts").install "lmromanslant17-regular.otf"
    (share/"fonts").install "lmromanslant8-regular.otf"
    (share/"fonts").install "lmromanslant9-regular.otf"
    (share/"fonts").install "lmromanunsl10-regular.otf"
    (share/"fonts").install "lmsans10-bold.otf"
    (share/"fonts").install "lmsans10-boldoblique.otf"
    (share/"fonts").install "lmsans10-oblique.otf"
    (share/"fonts").install "lmsans10-regular.otf"
    (share/"fonts").install "lmsans12-oblique.otf"
    (share/"fonts").install "lmsans12-regular.otf"
    (share/"fonts").install "lmsans17-oblique.otf"
    (share/"fonts").install "lmsans17-regular.otf"
    (share/"fonts").install "lmsans8-oblique.otf"
    (share/"fonts").install "lmsans8-regular.otf"
    (share/"fonts").install "lmsans9-oblique.otf"
    (share/"fonts").install "lmsans9-regular.otf"
    (share/"fonts").install "lmsansdemicond10-oblique.otf"
    (share/"fonts").install "lmsansdemicond10-regular.otf"
    (share/"fonts").install "lmsansquot8-bold.otf"
    (share/"fonts").install "lmsansquot8-boldoblique.otf"
    (share/"fonts").install "lmsansquot8-oblique.otf"
    (share/"fonts").install "lmsansquot8-regular.otf"
  end

  test do
  end
end
