class FontNotoSansMyanmar < Formula
  desc "Noto Sans Myanmar"
  homepage "https://www.google.com/get/noto/#sans-mymr"
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMyanmar-unhinted.zip"

  bottle :unneeded

  def install
    (share/"fonts").install "NotoSansMyanmar-Black.ttf"
    (share/"fonts").install "NotoSansMyanmar-Bold.ttf"
    (share/"fonts").install "NotoSansMyanmar-Condensed.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-CondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmar-ExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-Light.ttf"
    (share/"fonts").install "NotoSansMyanmar-Medium.ttf"
    (share/"fonts").install "NotoSansMyanmar-Regular.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmar-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmar-Thin.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Black.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Bold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Condensed.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-CondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensed.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraCondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-ExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Light.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Medium.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Regular.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensed.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedBlack.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedLight.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedMedium.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-SemiCondensedThin.ttf"
    (share/"fonts").install "NotoSansMyanmarUI-Thin.ttf"
  end

  test do
  end
end
