class FontPx437Pxplus < Formula
  desc "Px437"
  homepage "http://int10h.org/oldschool-pc-fonts/"
  url "http://int10h.org/oldschool-pc-fonts/download/ultimate_oldschool_pc_font_pack_v#{version}.zip"
  version "1.0"
  sha256 "7666cf23176e34ea03a218b5c1500f4ad729d97150ab7bdb7cf2adf4c99a9a7a"

  bottle :unneeded

  def install
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_AMI_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_AMI_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_8x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_8x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_8x8-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_8x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_9x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_9x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATI_SmallW_6x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATT_PC6300-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ATT_PC6300.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_AmstradPC1512-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_AmstradPC1512.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_CompaqThin_8x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_CompaqThin_8x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_CompaqThin_8x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_DTK_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_DTK_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_3270pc.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_BIOS-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_CGA-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_CGA.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_CGAthin-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_CGAthin.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_Conv-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_Conv-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_Conv.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_EGA8-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_EGA8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_EGA9-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_EGA9.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_ISO8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_ISO9.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_MDA.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PGC-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PGC.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PS2thin1.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PS2thin2.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PS2thin3.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_PS2thin4.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_VGA8-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_VGA8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_VGA9-2x.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_IBM_VGA9.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ITT_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ITT_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Kaypro2K.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Kaypro2k-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_PhoenixEGA_8x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_PhoenixEGA_8x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_PhoenixEGA_8x8-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_PhoenixEGA_8x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_PhoenixEGA_9x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Phoenix_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Phoenix_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyNew_225-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyNew_225.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyNew_Mono.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyNew_TV-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyNew_TV.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyOld_225-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyOld_225.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyOld_TV-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_TandyOld_TV.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ToshibaLCD_8x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_ToshibaLCD_8x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_VGA_SquarePx.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_VTech_BIOS-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_VTech_BIOS.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_8x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_8x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_8x8-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_8x8.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_9x14.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Verite_9x16.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Wyse700a-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Wyse700a.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Wyse700b-2y.ttf"
    (share/"fonts").install "Px437 (TrueType - DOS charset)/Px437_Wyse700b.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_AmstradPC1512-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_AmstradPC1512.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_BIOS-2x.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_BIOS-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_BIOS.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_CGA-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_CGA.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_CGAthin-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_CGAthin.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_EGA8-2x.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_EGA8.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_EGA9-2x.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_EGA9.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_MDA.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_VGA8-2x.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_VGA8.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_VGA9-2x.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_IBM_VGA9.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_TandyNew_225-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_TandyNew_225.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_TandyNew_TV-2y.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_TandyNew_TV.ttf"
    (share/"fonts").install "PxPlus (TrueType - extended charset)/PxPlus_VGA_SquarePx.ttf"
  end

  test do
  end
end
